### ISSUE TITLE
剧集能否批量下载字幕

### ISSUE THREAD

**Issue by laobanbiefangcu** [ChineseSubFinder/ChineseSubFinder#430]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 0.33.7

环境: docker 

## 你想要新增或者改进什么功能？
剧集能否批量下载字幕，一集一集点击加进队列有点麻烦

你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
新版本会对接机翻接口，顺带可以把这个也改进了。忍一忍，7月份应该能发布 [doge] @iMyon

**Comment by iMyon** [comment]
> 新版本会对接机翻接口，顺带可以把这个也改进了。忍一忍，7月份应该能发布 [doge] @iMyon

ok
