### ISSUE TITLE
配置文件巨大

### ISSUE THREAD

**Issue by fireflycao** [ChineseSubFinder/ChineseSubFinder#501]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
unraid dacker
不知道算不算bug
用了很久了，无意中发现config映射的chinesesubfinder文件夹巨大。改名为chinesesubfinder_back，10月1日重新建立一个现在运行不到24小时，已经30多G了。
![1](https://user-images.githubusercontent.com/20470524/193433011-afcd75c2-640d-478a-84c5-a0c3fc33b7f7.png)
![2](https://user-images.githubusercontent.com/20470524/193433015-888bc5f5-9cf1-4f83-95d1-6ace0e3b0947.jpg)

**Comment by goa1bit** [comment]
我docker安装的v0.40.1也这样，cache/CSF-SubFixCache目录中的文件有的就几十K，有的上百M：
![image](https://user-images.githubusercontent.com/34877903/193746600-8ce203fc-0623-43b2-a2b1-480a926f8d12.png)
<img width="482" alt="Snipaste_2022-10-04_14-14-47" src="https://user-images.githubusercontent.com/34877903/193747718-f2dd26b3-df29-45aa-ba90-d0d68746c34d.png">

**Comment by allanpk716** [comment]
矫正字幕的缓存，有自动清理机制。

**Comment by sapipoZZZ** [comment]
#504 咨询下如何关闭？是通过【自动校正字幕时间轴】里来关闭吗？

**Comment by fireflycao** [comment]
> 矫正字幕的缓存，有自动清理机制。

请问如何清理？
![Screenshot 2022-11-01 172634](https://user-images.githubusercontent.com/20470524/199202739-04558adf-3772-4a69-b7ed-d6cbc81ed643.jpg)

**Comment by allanpk716** [comment]
手动删除，重启

![image](https://user-images.githubusercontent.com/1176000/199240504-98b5abc1-d889-42a7-b6df-41dc8172c0bc.png)
