### ISSUE TITLE
无法下载美剧字幕

### ISSUE THREAD

**Issue by hexsen929** [ChineseSubFinder/ChineseSubFinder#512]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.40.1
>
> 环境: docker

无法下载美剧字幕，电影的可以正常下载

![image](https://user-images.githubusercontent.com/23308600/195511242-12a027ee-b273-4c8b-aac6-78ee7bc1059f.png)

![image](https://user-images.githubusercontent.com/23308600/195511558-b86e27b5-ecd5-473a-92bc-0764fd00c975.png)

目录设置正确，但是docker日志显示：
}[ERROR]: 2022-10-13 13:33:45 - decode.GetSeriesDirRootFPath == Empty, /media/TV/La Brea/La.Brea.S01E09.WEBRip.x264-ION10.mp4
j[INFO]: 2022-10-13 13:33:45 - you need check the directory structure of a series, so will delete this job
�[ERROR]: 2022-10-13 13:34:00 - decode.GetSeriesDirRootFPath == Empty, /media/TV/American.Gods.S03.1080p.BluRay.x265-RARBG/American.Gods.S03E06.1080p.BluRay.x265-RARBG.mp4
j[INFO]: 2022-10-13 13:34:00 - you need check the directory structure of a series, so will delete this job

**Comment by allanpk716** [comment]
你需要看连续剧的推荐目录结构，也只支持一种目录结构。首页文档中有说明。
