### ISSUE TITLE
关于字幕站绕过防爬虫信息

### ISSUE THREAD

**Issue by luotao21** [ChineseSubFinder/ChineseSubFinder#520]
请问这个项目的实现，是否能提供一些信息，用于绕过字幕站防攻击/爬虫等保护手段。
[https://github.com/FlareSolverr/FlareSolverr](url)

**Comment by allanpk716** [comment]
> 请问这个项目的实现，是否能提供一些信息，用于绕过字幕站防攻击/爬虫等保护手段。
> 
> [https://github.com/FlareSolverr/FlareSolverr](url)

暂时下限某些站点的原因是爬虫对于它们的压力太大，反爬虫不是很麻烦

**Comment by allanpk716** [comment]
可以使用最新版本试试

**Comment by luotao21** [comment]
太强大了，谢谢allanpk716
