### ISSUE TITLE
希望增加能对No Sub Found的某集手动上传字幕的功能

### ISSUE THREAD

**Issue by missing233** [ChineseSubFinder/ChineseSubFinder#536]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker

## 你想要新增或者改进什么功能？

字幕源网站能搜到的某一集对应字幕，下载队列里却提示No Sub Found。希望能增加对No Sub Found的某集手动上传字幕的功能。

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
升级最新的，有手动搜索和上传的功能。在"库"中
