### ISSUE TITLE
希望增加删除下载任务的功能

### ISSUE THREAD

**Issue by shucunbin** [ChineseSubFinder/ChineseSubFinder#541]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.43.1 Lite

环境: docker

## 你想要新增或者改进什么功能？

「删除/批量删除」 下载队列里的任务。目前使用将任务状态修改为「忽略」替代删除。

**Comment by allanpk716** [comment]
去“库”锁定视频。

**Comment by allanpk716** [comment]
这里单独解释一下为什么要这样设计，为何不提供删除下载任务的功能。

1. 本程序会持续不断的扫描可能需要下载字幕的任务，添加到队列；
2. 如果提供删除队列的功能，那么也就需要记录那些删除（还得要额外的管理删除后的队列页面）了，不能下载扫描添加队列；
3. 下载队列会有自身的清除逻辑，无需用户关心。设计的初衷是挂机，而不是频发的去关注
4. 现在提供的“库”，“锁定”一个视频的功能，意思就是跳过这个视频的字幕下载，其实也就是变现的“删除”下载任务；
5. 同时也可以选择一个任务，修改状态为，忽略。

大概基于上述的情况和原因，就不单独提供“删除”的功能。

**Comment by allanpk716** [comment]
当然最佳操作是，一旦你看完视频，就是“锁定”，后续就肯定不会再次自动下载了。当然这个肯定是麻烦的。所以建议配合 Emby 使用，并且设置“跳过已看”，那么 CSF 会自动进行管理，看完就不下载了。
