### ISSUE TITLE
因文件路径不是/media，导致无法保存新增TMDB API和ASSRT API设置

### ISSUE THREAD

**Issue by elle007011** [ChineseSubFinder/ChineseSubFinder#560]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.43.2
>
> 环境: Docker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 新增了两项设置，分别是保存TMDB API及保存ASSRT API。在选择设置后，提示后续设置需要将路径设置为/media下，但我的路径是/downloads/link下。导致在启动守护程序后无法保存这两个API

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 不要强制规定必须在/media下

**Comment by allanpk716** [comment]
docker 下必须，去看 docker 映射教程。

**Comment by elle007011** [comment]
可是我现在可以正常刷的出dian ying he dian shi ju_的媒体库啊_> docker 下必须，去看 docker 映射教程。

**Comment by allanpk716** [comment]
后续路径转换的时候就会出问题，请按提示去设置，否则后续不可预期的问题没法解决。
