### ISSUE TITLE
安装时无法填写电影和电视剧目录，一直提示目录不存在

### ISSUE THREAD

**Issue by ocxco** [ChineseSubFinder/ChineseSubFinder#562]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.43.2
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 安装时填写电影目录，一直提示目录不存在或者无权限。docker进入目录操作一切正常

## 你的问题能重现嘛？

> 一直重现

## 你期望的结果

> 能正确识别填写目录，完成设置。

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)
```json
未完成设置，放这里太占地方
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略
```shell
docker run -dti \
 --name chinesesubfinder \
 -c 50 \
 --hostname chinesesubfinder \
 --log-driver db \
 --network=bridge \
 -p 0.0.0.0:19035:19035/tcp \
 -p 0.0.0.0:19037:19037/tcp \
 --restart=always \
 -v /volume2/Media/links:/media:rw \
 -v /volume1/docker/chinesesub/config:/config:rw \
 -v /volume1/docker/chinesesub/browser:/root/.cache/rod/browser:rw \
 -w /config \
 allanpk716/chinesesubfinder:latest
```
## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图
![image](https://user-images.githubusercontent.com/3380467/203686750-0ef0969d-47cf-4b89-9378-322b981a39b5.png)
![image](https://user-images.githubusercontent.com/3380467/203686749-87ba17f2-26e0-4006-805e-d06f736a0e63.png)
![image](https://user-images.githubusercontent.com/3380467/203686979-df23986a-f44b-4d75-8746-d725636f7ae7.png)

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/203689011-982a7e01-68a0-4fac-a760-36eec749ef35.png)

看这个

**Comment by ocxco** [comment]
> ![image](https://user-images.githubusercontent.com/1176000/203689011-982a7e01-68a0-4fac-a760-36eec749ef35.png)
> 
> 看这个

跟目录结构没关系吧，如果我仓库里面还没有电影，就不能安装了吗。
我现在所有的视频目录都在/media下面，比如：/media/华语电影、 /media/外语电影、 /media/国产剧、/media/欧美剧，但是我电影目录设置/media/华语电影就是提示我目录不存在，只能写/media才行
是不是check_path这个函数只能识别第一级目录

**Comment by yanbinc** [comment]
同样的情况，
我看log文件会说没有权限。但我UPID和GPID 都改了1024 100 
在设置里面media->video 文件夹.
下面有TV_Series，Movie，Moive_Child 几个文件夹 都用TTM、Sonarr，Radarr 刷过。

但添加media/TV_Series 是就说不可用
特别把文件夹权限改成 everyone 可读写。

**Comment by allanpk716** [comment]
上面反馈问题的，你需要填写完整的 issues 反馈模板，不然需要，来回沟通几次，效率低。同时需要提供 Web F12 提交的请求信息。

**Comment by KITblue** [comment]
你们的问题可能是这样的，没有映射 media 目录，再映射子目录，比如：
![无标题](https://user-images.githubusercontent.com/68754977/206913045-f922f99d-442e-40a6-a535-ff2fc8a3421d.png)

如果省掉media一项，系统会自动创建一条存储卷（在docker内部），那样后面映射的media/XXX等目录就无法使用，因为media目录在docker内部，无法再同时映射到外部路径

**Comment by y1324** [comment]
我也是子目录提示么有权限，一级目录有权限，
![微信截图_20230422194808](https://user-images.githubusercontent.com/22168046/233782861-102ad8bb-1b6b-4f74-abad-8bac63bee10f.png)
![image](https://user-images.githubusercontent.com/22168046/233782904-eb33153d-3214-43ee-9ec2-e22f990986d6.png)

已经给这个账户权限了，但还是不行。

**Comment by y1324** [comment]
@allanpk716 麻烦看一下

**Comment by allanpk716** [comment]
> 我也是子目录提示么有权限，一级目录有权限， ![微信截图_20230422194808](https://user-images.githubusercontent.com/22168046/233782861-102ad8bb-1b6b-4f74-abad-8bac63bee10f.png) ![image](https://user-images.githubusercontent.com/22168046/233782904-eb33153d-3214-43ee-9ec2-e22f990986d6.png)
> 
> 已经给这个账户权限了，但还是不行。

1. 填写 issues 模板，什么运行环境都没说无法定位问题
2. 看主页教程

否则依然要反复沟通多次，请提高解决问题的效率

**Comment by allanpk716** [comment]
已经提示去看主页教程，教程明确提及不要嵌套添加资源路径，上面截图有明显路径设置的问题。

我的建议依然是看教程，举一反三。提供 issues 模板要求来提问。

教程有歧义，麻烦指出来，完善教程才能帮助更多的人。
