### ISSUE TITLE
url 校验问题

### ISSUE THREAD

**Issue by mygithello** [ChineseSubFinder/ChineseSubFinder#584]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.45.0
>
> 环境: docker
>

这里只能配置成ip形式，可以优化支持配置本地hosts映射成的域名吗？页面显示url校验问题
![image](https://user-images.githubusercontent.com/39377007/205475023-de0f05a0-ec4d-4e0d-a1ff-eebb12ac8e14.png)

**Comment by allanpk716** [comment]
试试：http://127.0.0.1:8096

**Comment by mygithello** [comment]
Ip 是没问题的，执行想用用hosts 里配置的映射
比如我hosts  中有 
192.168.2.243 localnas

**Comment by allanpk716** [comment]
@iMyon 这部的地址校验需要支持 localhost 关键词
