### ISSUE TITLE
能否支持多账号，或者支持一个账号同时在多台设备登录？

### ISSUE THREAD

**Issue by coolyzp** [ChineseSubFinder/ChineseSubFinder#590]
我在电视浏览器上打开csf，电脑上又打开，电视上就会被挤掉，输密码太麻烦了
或者登录界面能保存账号密码也可以

**Comment by allanpk716** [comment]
暂时没有打算支持多账号或者同时登录多台设备。但是如果你是局域网使用，完全可以更加简单的账号和密码组合，临时过度用一下。
