### ISSUE TITLE
电视剧多季情况下, 在非第一季上传一个字幕后, tab会切换到第一季

### ISSUE THREAD

**Issue by magicianShiro** [ChineseSubFinder/ChineseSubFinder#591]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.45.1 Lite
>
> 环境: docker
>

## 你遇到什么问题了？

> 电视剧多季情况下, 假如在第二季上上传了一个字幕, tab会跳转到第一季上
> [疑似该行代码导致](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/master/frontend/src/pages/library/tvs/DialogTVDetail.vue#L178)

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 电视剧在当前季上传字幕后, tab依旧停留在当前位置

**Comment by allanpk716** [comment]
@iMyon  需要帮看看
