### ISSUE TITLE
电视剧多选锁定字幕

### ISSUE THREAD

**Issue by CLOT-LIU** [ChineseSubFinder/ChineseSubFinder#593]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.45.1

环境:Docker版

## 你想要新增或者改进什么功能？

希望在这个页面加一个可以多选的功能，现在是每个都点进去才能锁定

![Snipaste_2022-12-22_00-10-57](https://user-images.githubusercontent.com/66453914/208950685-e3281fd2-37e9-4f5a-a778-932a997609cf.png)

希望可以有个多选的

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
这个提一下目前锁住的实现效果：是针对每一集进行锁定，也就是如果是正在更新的连续剧，那么批量锁住的逻辑其实也仅仅是锁住了当前已有的。这样实现是暂时没想好应该做到最终的功能效果，所以这样的实现比较简单粗暴。那么缺陷也是明显的。

这里是可以由前端来实现外层连续剧批量锁定的功能的，需要找 @iMyon  实现下

**Comment by iMyon** [comment]
> 这个提一下目前锁住的实现效果：是针对每一集进行锁定，也就是如果是正在更新的连续剧，那么批量锁住的逻辑其实也仅仅是锁住了当前已有的。这样实现是暂时没想好应该做到最终的功能效果，所以这样的实现比较简单粗暴。那么缺陷也是明显的。
> 
> 这里是可以由前端来实现外层连续剧批量锁定的功能的，需要找 @iMyon 实现下

纯前端选了10部剧可能就要发几百个请求，只能说可以实现，后面可以给个批量接口

**Comment by allanpk716** [comment]
将在 0.47 给出这个功能

**Comment by allanpk716** [comment]
升级最新
