### ISSUE TITLE
有些剧能整季搜索到字幕，无法单集搜索到字幕

### ISSUE THREAD

**Issue by Passerby1011** [ChineseSubFinder/ChineseSubFinder#599]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.46.3 Lite

环境: docker

有些剧能整季搜索到字幕，无法单集搜索到字幕，整季的字幕手动搜索是能搜到的，是以压缩包的形式整季存在的，但是chinesesubfinder在搜索字幕时都是以单集进行搜索的，所以很多时候都无法搜索到不是很新的电视剧和动漫的字幕，只能进行手动匹配

**Comment by allanpk716** [comment]
你是在什么地方搜索的？新的规划是私有的字幕源，也许可以解决你遇到的问题。

**Comment by Passerby1011** [comment]
就是自带的a4k

**Comment by allanpk716** [comment]
升级最新
