### ISSUE TITLE
【建议】能否增加一个开关，可以选择把缓存的字幕文件等数据放到对应的影视作品的目录下

### ISSUE THREAD

**Issue by alexcdever** [ChineseSubFinder/ChineseSubFinder#604]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.46.3
>
> 环境: docker

## 你遇到什么问题了？

> 希望可以配置项那里增加一个开关，可以选择把缓存的字幕文件等数据放到对应的影视作品的目录下。可能因为我的影视作品太多的缘故，我发现缓存数据已经去到30多GB了，而我专门用来跑服务的虚拟机的系统盘并不大，可以划分给虚拟机的空间并不多，现在快满了。但是我的NAS还有充足的空间，不介意缓存数据跟着影视作品。

**Comment by kxs2018** [comment]
把存放影视的目录映射给/media不就行了吗？比如    
```
volumes:
    - /srv/dev-disk-by-uuid-764ea778-6da0-4d5a-b98d-df09f2a4e1b7/影视/hlink:/media 
```
![未命名1673867372](https://user-images.githubusercontent.com/82091384/212664587-38ebab61-be54-4a06-9b63-c6e026115694.png)

**Comment by alexcdever** [comment]
```
volumes:
      - ./chinesesubfinder/config:/config # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mnt/nas/media:/media
      - ./browser:/root/.cache/rod/browser # 容器重启后无需再次下载 chrome，除非 go-rod 更新
```

作者你好，上面这里就是我现在的配置，media这部分我配置了，但我说的缓存是指config那里面的cache目录下的东西。
昨晚跟你反馈之后，我尝试做了一些补救动作：
- 清空cache
- 将扫描间隔拉到最大（10小时）
- 关闭‘保存整季的缓存字幕’
- ‘下载缓存过期时间’设置成72小时
- ‘设备性能选择’改为‘一般’
现在的话，好像好很多了，当下占用变成了5G多，如图：
![image](https://user-images.githubusercontent.com/14200813/212713150-eebf460d-e8dc-450b-acbb-fbbf23a89501.png)

回过头来想的话，可能是缓存没有及时被清除的缘故。

**Comment by allanpk716** [comment]
下载字幕的缓存其实不会那么大，大的缓存是自动矫正时间轴的音频缓存（我记得是一周没有访问就删除）。

你如果是使用 docker ，可以指定缓存的目录到你可以接受的位置。我记得新版本也支持传参启动指定配置目录了（针对直接运行部分的情况）。
