### ISSUE TITLE
字幕下载的是完全错误的电影

### ISSUE THREAD

**Issue by ChanceLuo** [ChineseSubFinder/ChineseSubFinder#609]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.46.3
>
> 环境: docker

## 你遇到什么问题了？

> 这应该是assrt搜索的问题（不清楚其他字幕站有没有类似的问题），默认排序会列出完全不相干的电影，导致下载了完全错误的字幕（已附上log），比如：
![image](https://user-images.githubusercontent.com/12534772/215161217-40e668a2-a403-487d-bc29-f4a05e5d7fe3.png)

> 如果按相关度排序，结果会更准确些：
![image](https://user-images.githubusercontent.com/12534772/215163061-b77c9a3a-c55a-4dcc-a67a-7a8780ca26a8.png)

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 最好程序内部有个连续字符匹配来确保下载的字幕是正确的，如果完全依赖网站的搜索结果那么很容易出现错误匹配，而下载到错误字幕要比没找到字幕还要麻烦。如果严格连续匹配会影响部分用户，那么可以改成选项让用户自己选择是否开启。

> 即使不加以上功能，对于assrt来说，最好也是优先用相关度排序的结果。

## 请给出当次问题的完整日志
> [cs.log](https://github.com/ChineseSubFinder/ChineseSubFinder/files/10521755/cs.log)

**Comment by allanpk716** [comment]
基于关键词搜索，且结果资源没有 IMDB ID 做基准比对的时候就会出现这个问题。我倾向于弱化这种类型搜索的字幕源，已经在做私有字幕源来解决类似问题。基于的是 IMDB ID，就算错了，也有办法在我的后台管理这些问题。
