### ISSUE TITLE
能不能给个跳过”强制放在MEDIA“目录下的选项？？

### ISSUE THREAD

**Issue by toniexly** [ChineseSubFinder/ChineseSubFinder#610]
软件运行在Docker中，请将基础设置中的电影和电视剧目录修改为 /media 下的目录，否则可能会因为权限问题导致无法正确的加载媒体库。

不这样设不能进行下一步，权限问题的麻烦我理解，但是是否在警告后给个跳过的选项。。。
应该很多老鸟跟我一样，资源放在好几个地方，也有自己的组织资源习惯，权限问题我会自己解决，解决不了不来烦您，可否给个强警告好后给个跳过后果自负的选项？

**Comment by toniexly** [comment]
哦可不用解答我，已解决

**Comment by Ton-yi** [comment]
挺巧也遇到这个问题，我觉得在设置时明说 “不为/media可能有权限问题” 就好，
我摸索了半天才知道意识到原来docker挂载目录可以聚合的 orz
![image](https://user-images.githubusercontent.com/73752817/215294328-d2e8817e-e89e-45a2-b089-320b5eb51846.png)
