### ISSUE TITLE
锁定单个剧集功能

### ISSUE THREAD

**Issue by paracide** [ChineseSubFinder/ChineseSubFinder#614]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.46.3

环境: docker

## 你想要新增或者改进什么功能？

增加一个锁定单个剧集功能
例如海贼王有21季,但我不需要CSF下载字幕,目前锁定的话,需要把21季每季点过去全选锁定,操作繁琐

## 这个功能有什么可以参考的资料吗？

参考电影列表的锁定

**Comment by iMyon** [comment]
和 #593 重复了，这几天会加上
