### ISSUE TITLE
剧集列表中99集之后的集数,显示00集

### ISSUE THREAD

**Issue by paracide** [ChineseSubFinder/ChineseSubFinder#615]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vv0.46.3
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 剧集列表一季超过99集的话,100+的显示00集,在长篇动画中普遍存在
![QQ图片20230204173835](https://user-images.githubusercontent.com/11735234/216760175-ef7249ab-ab1f-44f5-bae2-a4e6f63c962d.png)
![QQ图片20230204173846](https://user-images.githubusercontent.com/11735234/216760176-7ac04c81-9182-4877-b3ad-8bed8665b4bd.png)

**Comment by allanpk716** [comment]
你可以截图你这部分资源的文件里列表来看看吗？我看看是否是解析文件名第几集的代码导致的。

**Comment by paracide** [comment]
> 你可以截图你这部分资源的文件里列表来看看吗？我看看是否是解析文件名第几集的代码导致的。
![1](https://user-images.githubusercontent.com/11735234/216913598-17f5ef51-bfa7-4516-94e6-c3a5a8bf1943.png)
![2](https://user-images.githubusercontent.com/11735234/216913611-2bac0658-9aa7-4370-9613-3afe731c3ff1.png)

**Comment by allanpk716** [comment]
项目使用了第三方的文件名解析库（使用这个库是为了解析一些变态的文件名情况），它不支持百位数的 Season 和 Episode。我需要看看改了会有啥问题没有先。

还有一些 Season 和 Eps 识别是我写的，可以修复，但是牵扯其他的逻辑，估计得慢慢找一下，怕漏了。

**Comment by paracide** [comment]
> 项目使用了第三方的文件名解析库（使用这个库是为了解析一些变态的文件名情况），它不支持百位数的 Season 和 Episode。我需要看看改了会有啥问题没有先。
> 
> 还有一些 Season 和 Eps 识别是我写的，可以修复，但是牵扯其他的逻辑，估计得慢慢找一下，怕漏了。

修复的同时顺便支持下千位数的,海贼王等长篇动画集数已经破千了

**Comment by allanpk716** [comment]
我看了下第三方的代码，尝试改了，出了新的问题。我考虑下还是自己统一维护一个视频名称解析的模块吧。争取 0.47 发布
