### ISSUE TITLE
总览页面中强制停止点击无效

### ISSUE THREAD

**Issue by LoadingMx** [ChineseSubFinder/ChineseSubFinder#618]
环境如下：
系统：Mac 13.1 
浏览器：Safari浏览器 版本16.2
安装软件版本：v0.46.3 (ChineseSubFinder)

问题：
总览-强制停止，点击无效、无法弹出确认窗口

浏览器换成 Chrome 正常使用。问题应该是 Safari 适配上

**Comment by allanpk716** [comment]
方便在 safari 点击停止的时候，看看 F12 的网络通信吗？

**Comment by iMyon** [comment]
修复了，下次发版会加上。应该是safari浏览器自己的BUG，我的建议是，别用safari
#quasarframework/quasar/issues/14779
