### ISSUE TITLE
v1/preview/search_other_web

### ISSUE THREAD

**Issue by jerry-f** [ChineseSubFinder/ChineseSubFinder#622]
## 你使用的 chinesesubfinder 是什么版本 v0.46.3，什么环境:docker

> chinesesubfinder 版本: v0.46.3
>
> 环境: docker Linux 
>
> 在程序运行日志头部或者 Web UI 可以看到

## v1/preview/search_other_web 点击搜索的时候报错：
{"message":"no metadata file, movie.xml or *.nfo"}，导致不能查询字幕

载荷为： 
{
"video_f_path":"/media/电影/Black Panther Wakanda Forever 2022 1080p HDTS x264 1.7GB - HushRips/Black Panther Wakanda Forever 2022 1080p HDTS x264 1.7GB - HushRips.mkv",
"is_movie":true
}

**Comment by allanpk716** [comment]
你这个电影缺失削刮后的信息

**Comment by jerry-f** [comment]
是电影的目录里面有一个 xml 文件信息么，还是 “ChineseSubFinder” 配置里面需要一个配置信息没有填写。

**Comment by allanpk716** [comment]
你可以搜索 TMM 关键词，是一个削刮工具。会在一个电影下生成 movie.xml 这样的信息。
