### ISSUE TITLE
TMDB api异常，无法访问

### ISSUE THREAD

**Issue by kewell2000** [ChineseSubFinder/ChineseSubFinder#626]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.46.3 Lite 
>
> 环境:  群晖套件中心安装
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？
TMDB api异常，无法访问
> 描述一下你遇到的问题
填入TMDB API后检测提示连接异常
## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果
如何解决无法连接的问题

## 给出当前程序的配置文件

{
  "SpeedDevMode": false,
  "user_info": {
    "username": "",
    "password": ""
  },
  "common_settings": {
    "interval_or_assign_or_custom": 0,
    "scan_interval": "@every 4h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": [
      "/media/link/电影"
    ],
    "series_paths": [
      "/media/link/电视剧"
    ],
    "local_static_file_port": "19037"
  },
  "subtitle_sources": {
    "assrt_settings": {
      "enabled": true,
      "token": ""
    }
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_proxy": false,
      "use_which_proxy_protocol": "http",
      "local_http_proxy_server_port": "49156",
      "input_proxy_address": "127.0.0.1",
      "input_proxy_port": "9090",
      "need_pwd": false,
      "input_proxy_username": "",
      "input_proxy_password": ""
    },
    "tmdb_api_settings": {
      "enable": true,
      "api_key": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": false,
    "sub_type_priority": 0,
    "sub_name_formatter": 1,
    "save_multi_sub": false,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1,
    "suppliers_settings": {
      "csf": {
        "name": "csf",
        "root_url": "haha",
        "search_url": "haha",
        "daily_download_limit": -1
      },
      "xunlei": {
        "name": "xunlei",
        "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
        "search_url": "",
        "daily_download_limit": -1
      },
      "shooter": {
        "name": "shooter",
        "root_url": "https://www.shooter.cn/api/subapi.php",
        "search_url": "",
        "daily_download_limit": -1
      },
      "subhd": {
        "name": "subhd",
        "root_url": "https://subhd.tv",
        "search_url": "/search/%s",
        "daily_download_limit": 20
      },
      "zimuku": {
        "name": "zimuku",
        "root_url": "https://zimuku.org",
        "search_url": "/search?q\u003d%s",
        "daily_download_limit": 20
      },
      "assrt": {
        "name": "assrt",
        "root_url": "https://api.assrt.net/v1",
        "search_url": "",
        "daily_download_limit": -1
      },
      "a4k": {
        "name": "a4k",
        "root_url": "https://www.a4k.net",
        "search_url": "/search?term\u003d",
        "daily_download_limit": -1
      }
    },
    "scan_logic": {
      "skip_chinese_movie": false,
      "skip_chinese_series": false
    },
    "task_queue": {
      "max_retry_times": 3,
      "one_job_time_out": 300,
      "interval": 10,
      "expiration_time": 90,
      "download_sub_during_x_days": 7,
      "one_sub_download_interval": 12,
      "check_pulic_ip_target_site": ""
    },
    "download_file_cache": {
      "ttl": 4320,
      "unit": "hour"
    }
  },
  "emby_settings": {
    "enable": false,
    "address_url": "",
    "api_key": "",
    "max_request_video_number": 500,
    "skip_watched": false,
    "movie_paths_mapping": {
      "/media/link/电影": ""
    },
    "series_paths_mapping": {
      "/media/link/电视剧": ""
    },
    "auto_or_manual": true,
    "threads": 4
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 700,
    "min_offset": 0.2
  },
  "experimental_function": {
    "auto_change_sub_encode": {
      "enable": false,
      "des_encode_type": 0
    },
    "chs_cht_changer": {
      "enable": false,
      "des_chinese_language_type": 0
    },
    "remote_chrome_settings": {
      "enable": false,
      "remote_docker_url": "",
      "remote_adblock_path": "",
      "remote_user_data_dir": ""
    },
    "api_key_settings": {
      "enabled": true,
      "key": ""
    },
    "local_chrome_settings": {
      "enabled": false,
      "local_chrome_exe_f_path": ""
    },
    "share_sub_settings": {
      "share_sub_enabled": false
    },
    "extend_log": {
      "SysLog": {
        "enable": false,
        "network": "",
        "address": "",
        "priority": 0,
        "tag": ""
      }
    }
  }
}

## 如果是使用 Docker，请给出对应的配置信息
通过群晖套件中心安装的chinesesubfinder
> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
[INFO]: 2023-02-21 13:24:03 - ChineseSubFinder Version: v0.46.3
[INFO]: 2023-02-21 13:24:07 - Reload Log Settings, level = Info
[INFO]: 2023-02-21 13:24:07 - Speed Dev Mode is Off
[INFO]: 2023-02-21 13:24:07 - PreJob.HotFix() Start...
[INFO]: 2023-02-21 13:24:07 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-02-21 13:24:07 - PreJob.HotFix() End
[INFO]: 2023-02-21 13:24:07 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2023-02-21 13:24:07 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-02-21 13:24:07 - AutoDetectThenChangeTo Movie Index 0 /media/link/电影 Start
[WARNING]: 2023-02-21 13:24:07 - IsSubHasChinese.HasChineseLang /media/link/电影/外语电影/盗梦空间 (2010)/盗梦空间 (2010) - 1080p.eng.srt not chinese sub, is  英
[ERROR]: 2023-02-21 13:24:07 - DetermineFileTypeFromFile /media/link/电影/外语电影/盗梦空间 (2010)/盗梦空间 (2010) - 1080p.srt unsupport srcCharset: 
[INFO]: 2023-02-21 13:24:07 - AutoDetectThenChangeTo Movie Index 0 /media/link/电影 Start
[INFO]: 2023-02-21 13:24:07 - AutoDetectThenChangeTo Series Index 0 /media/link/电视剧 Start
[WARNING]: 2023-02-21 13:24:07 - IsSubHasChinese.HasChineseLang /media/link/电视剧/华语电影/三体 (2023)/三体 (2023).srt not chinese sub, is  英
[INFO]: 2023-02-21 13:24:07 - AutoDetectThenChangeTo Series Index 0 /media/link/电视剧 Start
[INFO]: 2023-02-21 13:24:08 - PreJob.ChangeSubNameFormat() End
[INFO]: 2023-02-21 13:24:08 - PreJob.ReloadBrowser() Start...
[INFO]: 2023-02-21 13:24:08 - releaseAdblock start
[INFO]: 2023-02-21 13:24:09 - releaseAdblock end
[INFO]: 2023-02-21 13:24:27 - PreJob.ReloadBrowser() End
[INFO]: 2023-02-21 13:24:27 - PreJob.Wait() Done.
[INFO]: 2023-02-21 13:24:31 - Download.SupplierCheck() Start ...
[INFO]: 2023-02-21 13:24:31 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-02-21 13:24:31 - PreDownloadProcess.Init() Start...
[INFO]: 2023-02-21 13:24:32 - GetCode 2023-02-21 926481
[INFO]: 2023-02-21 13:24:32 - ClearRodTmpRootFolder Done
[INFO]: 2023-02-21 13:24:32 - PreDownloadProcess.Init() End
[INFO]: 2023-02-21 13:24:32 - PreDownloadProcess.Check() Start...
[INFO]: 2023-02-21 13:24:32 - UseHttpProxy = false
[INFO]: 2023-02-21 13:24:33 - UrlConnectednessTest Target Site https://baidu.com Speed: 434 ms, Status: true
[INFO]: 2023-02-21 13:24:33 - Check Sub Supplier Start...
[INFO]: 2023-02-21 13:24:33 - xunlei Check Alive = true, Speed = 268 ms
[INFO]: 2023-02-21 13:24:35 - shooter Check Alive = true, Speed = 1938 ms
[INFO]: 2023-02-21 13:24:36 - a4k Check Alive = true, Speed = 945 ms
[INFO]: 2023-02-21 13:24:36 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 4
[INFO]: 2023-02-21 13:24:36 - assrt Check Alive = true, Speed = 505 ms
[INFO]: 2023-02-21 13:24:36 - Alive Supplier: xunlei
[INFO]: 2023-02-21 13:24:36 - Alive Supplier: shooter
[INFO]: 2023-02-21 13:24:36 - Alive Supplier: a4k
[INFO]: 2023-02-21 13:24:36 - Alive Supplier: assrt
[INFO]: 2023-02-21 13:24:36 - Check Sub Supplier End
[INFO]: 2023-02-21 13:24:36 - MovieFolder Index 0 -- /media/link/电影
[INFO]: 2023-02-21 13:24:36 - SeriesPaths Index 0 -- /media/link/电视剧
[INFO]: 2023-02-21 13:24:36 - PreDownloadProcess.Check() End
[INFO]: 2023-02-21 13:24:36 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-02-21 13:24:36 - Download.SupplierCheck() End
[INFO]: 2023-02-21 13:24:36 - Setup is Done
[INFO]: 2023-02-21 13:24:36 - RunAtStartup: false, so will not Run At Startup
[INFO]: 2023-02-21 13:24:36 - CronHelper Start...
[INFO]: 2023-02-21 13:24:36 - Next Sub Scan Will Process At: 2023-02-21 17:24:36

**Comment by allanpk716** [comment]
see #607

**Comment by allanpk716** [comment]
升级最新，支持了国内大部分可用的 tmdb 的 api 地址
