### ISSUE TITLE
无法识别某电视剧的剧集内容 【已刮削，其他电视剧正常】

### ISSUE THREAD

**Issue by andyandybeginner** [ChineseSubFinder/ChineseSubFinder#627]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.46.3
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 描述一下你遇到的问题
电视剧文件夹里很多电视剧。其中只有一部电视剧，含有三季内容，webui里在电视剧列表里只能看到封面，无法探查里面包含了多少集。其他电视均正常。所有电视剧命名方式和刮削均一致。

## 你的问题弄重现嘛？
一直存在
> 能够重新，不能够重现

## 你期望的结果

> 描述以下你期望的结果
可以正确识别电视剧，并且识别出季，以便我使用CSF的功能上传字幕。
## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "user_info": {
    "username": "xx", // 这里是用户名，需要替换掉
    "password": "xx" // 这里是密码，需要替换掉
  },
  "common_settings": {
    "scan_interval": "6h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": ["X:\\电影"],
    "series_paths": ["X:\\连续剧"]
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": false,
      "http_proxy_address": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://192.168.50.xxx:xxx", // 这里替换掉
    "api_key": "xxxxxxxxxxxxxx", // 这里替换掉
    "max_request_video_number": 100,
    "skip_watched": true,
    "movie_paths_mapping": {
      "X:\\电影": "/mnt/share1/电影"
    },
    "series_paths_mapping": {
      "X:\\连续剧": "/mnt/share1/连续剧"
    }
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by allanpk716** [comment]
有问题的连续剧目录结构截图

**Comment by tabris233** [comment]
> 有问题的连续剧目录结构截图

hi~ @allanpk716 我遇到的问题貌似和 @andyandybeginner 的是一个问题。具体表现为某个连续剧不显示第几季。

![image](https://user-images.githubusercontent.com/29500388/230739061-4d530467-5ddc-4c39-af9a-a5a940b87e02.png)

初步看了下 `/v1/video/list/one_series_subs` 返回的 `one_video_info` 为空。 

![image](https://user-images.githubusercontent.com/29500388/230739117-9bff648b-5a6b-43e4-8cc0-616d0707183d.png)

看起来是因为这部剧的视频格式比较特殊是 `.ts` , 不在支持的格式列表中。然后用户自定义格式的配置刚好未生效，setting 中的配置没有赋值给用到的变量(`_customVideoExts `)，就给忽略了。

![image](https://user-images.githubusercontent.com/29500388/230739132-3220948d-36d6-44f4-b4c3-c1614ea754ad.png)


https://github.com/ChineseSubFinder/ChineseSubFinder/blob/449f3681950bf20b569d86cb00adadf80187a3c7/pkg/util.go#L247-L249

（本想提个 PR，然而我搞了一会还没编译过，还是请大佬辛苦帮忙看下是不是这里需要调整哈~

**Comment by allanpk716** [comment]
issues 的提出者没有反馈新的消息，先关闭此 issues，有问题优先请升级最新。

**Comment by andyandybeginner** [comment]
> > 有问题的连续剧目录结构截图
> 
> hi~ @allanpk716 我遇到的问题貌似和 @andyandybeginner 的是一个问题。具体表现为某个连续剧不显示第几季。
> 
> ![image](https://user-images.githubusercontent.com/29500388/230739061-4d530467-5ddc-4c39-af9a-a5a940b87e02.png)
> 
> 初步看了下 `/v1/video/list/one_series_subs` 返回的 `one_video_info` 为空。
> 
> ![image](https://user-images.githubusercontent.com/29500388/230739117-9bff648b-5a6b-43e4-8cc0-616d0707183d.png)
> 
> 看起来是因为这部剧的视频格式比较特殊是 `.ts` , 不在支持的格式列表中。然后用户自定义格式的配置刚好未生效，setting 中的配置没有赋值给用到的变量(`_customVideoExts `)，就给忽略了。
> 
> ![image](https://user-images.githubusercontent.com/29500388/230739132-3220948d-36d6-44f4-b4c3-c1614ea754ad.png)
> 
> https://github.com/ChineseSubFinder/ChineseSubFinder/blob/449f3681950bf20b569d86cb00adadf80187a3c7/pkg/util.go#L247-L249
> 
> （本想提个 PR，然而我搞了一会还没编译过，还是请大佬辛苦帮忙看下是不是这里需要调整哈~

谢谢帮忙解释。能力有限没法解释的这么清楚。
