### ISSUE TITLE
无法下载字幕

### ISSUE THREAD

**Issue by songzijiang** [ChineseSubFinder/ChineseSubFinder#632]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.47.4 Lite
>
> 环境: docker 32位arm
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 1.无法立刻开始下载字幕。可以添加下载任务，但是一直处于等待下载，要过很久才会进入下载中
> 2.字幕下载失败，进入下载任务的字幕会失败很多次才有可能成功。如果是因为字幕没搜到，我觉得钢铁侠这么火的字幕不应该搜索不到。
>web ui日志如下：
[WARNING]: 2023-03-14 11:46:08 - cancel Downloader.QueueDownloader()
[WARNING]: 2023-03-14 13:19:09 - cancel Downloader.QueueDownloader()
[WARNING]: 2023-03-14 13:19:24 - cancel Downloader.QueueDownloader()

## 你的问题弄重现嘛？

> 能够重新

## 给出当前程序的配置文件
```json
{
	"SpeedDevMode": false,
	"user_info": {
		"username": "",
		"password": ""
	},
	"common_settings": {
		"interval_or_assign_or_custom": 2,
		"scan_interval": "@every 87600h",
		"threads": 3,
		"run_scan_at_start_up": false,
		"movie_paths": [
			"/media/movies"
		],
		"series_paths": [
			"/media/tvseries",
			"/media/comic"
		],
		"local_static_file_port": ""
	},
	"subtitle_sources": {
		"assrt_settings": {
			"enabled": true,
			"token": ""
		},
		"subtitle_best_settings": {
			"enabled": false,
			"api_key": ""
		}
	},
	"advanced_settings": {
		"proxy_settings": {
			"use_proxy": false,
			"use_which_proxy_protocol": "http",
			"local_http_proxy_server_port": "19036",
			"input_proxy_address": "127.0.0.1",
			"input_proxy_port": "10809",
			"need_pwd": false,
			"input_proxy_username": "",
			"input_proxy_password": ""
		},
		"tmdb_api_settings": {
			"enable": false,
			"api_key": ""
		},
		"debug_mode": false,
		"save_full_season_tmp_subtitles": false,
		"sub_type_priority": 0,
		"sub_name_formatter": 1,
		"save_multi_sub": false,
		"custom_video_exts": [],
		"fix_time_line": false,
		"topic": 1,
		"suppliers_settings": {
			"xunlei": {
				"name": "xunlei",
				"root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
				"search_url": "",
				"daily_download_limit": -1
			},
			"shooter": {
				"name": "shooter",
				"root_url": "https://www.shooter.cn/api/subapi.php",
				"search_url": "",
				"daily_download_limit": -1
			},
			"assrt": {
				"name": "assrt",
				"root_url": "https://api.assrt.net/v1",
				"search_url": "",
				"daily_download_limit": -1
			},
			"a4k": {
				"name": "a4k",
				"root_url": "https://www.a4k.net",
				"search_url": "/search?term=",
				"daily_download_limit": -1
			},
			"subhd": {
				"name": "subhd",
				"root_url": "https://subhd.tv",
				"search_url": "/search/%s",
				"daily_download_limit": 20
			},
			"zimuku": {
				"name": "zimuku",
				"root_url": "https://zimuku.org",
				"search_url": "/search?q=%s",
				"daily_download_limit": 20
			}
		},
		"scan_logic": {
			"skip_chinese_movie": false,
			"skip_chinese_series": false
		},
		"task_queue": {
			"max_retry_times": 3,
			"one_job_time_out": 300,
			"interval": 10,
			"expiration_time": 90,
			"download_sub_during_x_days": 7,
			"one_sub_download_interval": 12,
			"check_pulic_ip_target_site": ""
		},
		"download_file_cache": {
			"ttl": 4320,
			"unit": "hour"
		}
	},
	"emby_settings": {
		"enable": false,
		"address_url": "",
		"api_key": "",
		"max_request_video_number": 500,
		"skip_watched": false,
		"movie_paths_mapping": {
			"/media/movies": ""
		},
		"series_paths_mapping": {
			"/media/comic": "",
			"/media/tvseries": ""
		},
		"auto_or_manual": true,
		"threads": 3
	},
	"developer_settings": {
		"enable": false,
		"bark_server_address": ""
	},
	"timeline_fixer_settings": {
		"max_offset_time": 700,
		"min_offset": 0.2
	},
	"experimental_function": {
		"auto_change_sub_encode": {
			"enable": false,
			"des_encode_type": 0
		},
		"chs_cht_changer": {
			"enable": false,
			"des_chinese_language_type": 0
		},
		"remote_chrome_settings": {
			"enable": false,
			"remote_docker_url": "",
			"remote_adblock_path": "",
			"remote_user_data_dir": ""
		},
		"api_key_settings": {
			"enabled": true,
			"key": ""
		},
		"local_chrome_settings": {
			"enabled": false,
			"local_chrome_exe_f_path": ""
		},
		"share_sub_settings": {
			"share_sub_enabled": false
		},
		"extend_log": {
			"SysLog": {
				"enable": false,
				"network": "",
				"address": "",
				"priority": 0,
				"tag": ""
			}
		}
	}
}
```

## 如果是使用 Docker，请给出对应的配置信息

> docker-compose.taml
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /usr/share/nginx/raspberry/files/chineseSubTitle/config:/config
      - /mnt/ssd2/cache:/root/.cache/rod/browser
      - /mnt/sg16t/share/downloads/links/comic:/media/comic
      - /mnt/sg16t/share/downloads/links/movies:/media/movies
      - /mnt/sg16t/share/downloads/links/tvseries:/media/tvseries
      - /mnt/wd16t/movie:/mnt/wd16t/movie
      - /mnt/wd16t/comic:/mnt/wd16t/comic
      - /mnt/wd16t/tvshow:/mnt/wd16t/tvshow
    restart: always
    network_mode: "host"
    privileged: true
    container_name: chinesesubfinder
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整
## 给出媒体文件夹的目录结构
> 使用的是nastool刮削，jellyfin可以正确识别

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> [INFO]: 2023-03-14 11:45:53 - RunAtStartup: false, so will not Run At Startup
[INFO]: 2023-03-14 11:45:53 - CronHelper Start...
[INFO]: 2023-03-14 11:45:53 - Next Sub Scan Will Process At: 2023-03-14 16:45:53
[INFO]: 2023-03-14 11:46:08 - ------------------------------------------
[INFO]: 2023-03-14 11:46:08 - OneTimeSubtitleScanStart#50c0d6e973b1959196fcf92760f511cc74424d990609439719964dc921c49b78
[WARNING]: 2023-03-14 11:46:08 - cancel Downloader.QueueDownloader()
[INFO]: 2023-03-14 11:46:08 - OneTimeSubtitleScanEnd
[INFO]: 2023-03-14 11:46:08 - ------------------------------------------
[INFO]: 2023-03-14 11:46:08 - Queue 1 DlSub Start /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 11:46:08 - Queue 1 xunlei /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 11:46:08 - Queue 1 xunlei Start...
[INFO]: 2023-03-14 11:46:08 - Queue 1 xunlei End...
[INFO]: 2023-03-14 11:46:08 - Queue 1 shooter /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 11:46:08 - Queue 1 shooter Start...
[INFO]: 2023-03-14 11:46:09 - Queue 1 shooter End...
[INFO]: 2023-03-14 11:46:09 - Queue 1 a4k /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 11:46:09 - Queue 1 a4k Start...
[WARNING]: 2023-03-14 11:46:10 - status code: 502
[ERROR]: 2023-03-14 11:46:10 - a4k GetMixMediaInfo SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 11:46:10 - Queue 1 a4k End...
[ERROR]: 2023-03-14 11:46:10 - Queue 1 a4k oneMovieDlSubInOneSite SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 11:46:10 - Queue 1 assrt /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 11:46:10 - Queue 1 assrt Start...
[WARNING]: 2023-03-14 11:46:11 - status code: 502
[ERROR]: 2023-03-14 11:46:11 - assrt /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv GetMixMediaInfo SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 11:46:11 - Queue 1 assrt End...
[ERROR]: 2023-03-14 11:46:11 - Queue 1 assrt oneMovieDlSubInOneSite SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 11:46:11 - Queue 1 DlSub End /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[WARNING]: 2023-03-14 11:46:11 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2023-03-14 11:46:11 - No Sub Found 钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 11:48:53 - VideoScanAndRefreshHelper is not running
[INFO]: 2023-03-14 11:48:53 - Downloader.Cancel()
[INFO]: 2023-03-14 11:48:53 - CronHelper.Stop() context<-Done.
[INFO]: 2023-03-14 11:48:53 - CronHelper.Stop() Done.
[INFO]: 2023-03-14 11:53:31 - VideoScanAndRefreshHelper is not running
[INFO]: 2023-03-14 11:53:31 - Http Server Shutdown Successfully
[INFO]: 2023-03-14 11:53:31 - Http Server Shutdown Done.
[INFO]: 2023-03-14 11:53:31 - Try Start Http Server At Port 19035
[INFO]: 2023-03-14 13:18:54 - RunAtStartup: false, so will not Run At Startup
[INFO]: 2023-03-14 13:18:54 - CronHelper Start...
[INFO]: 2023-03-14 13:18:54 - Next Sub Scan Will Process At: 2033-03-11 13:18:54
[INFO]: 2023-03-14 13:19:09 - ------------------------------------------
[INFO]: 2023-03-14 13:19:09 - OneTimeSubtitleScanStart#50c0d6e973b1959196fcf92760f511cc74424d990609439719964dc921c49b78
[WARNING]: 2023-03-14 13:19:09 - cancel Downloader.QueueDownloader()
[INFO]: 2023-03-14 13:19:09 - OneTimeSubtitleScanEnd
[INFO]: 2023-03-14 13:19:09 - ------------------------------------------
[INFO]: 2023-03-14 13:19:09 - Queue 1 DlSub Start /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:09 - Queue 1 xunlei /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:09 - Queue 1 xunlei Start...
[INFO]: 2023-03-14 13:19:09 - Queue 1 xunlei End...
[INFO]: 2023-03-14 13:19:09 - Queue 1 shooter /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:09 - Queue 1 shooter Start...
[INFO]: 2023-03-14 13:19:09 - Queue 1 shooter End...
[INFO]: 2023-03-14 13:19:09 - Queue 1 a4k /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:09 - Queue 1 a4k Start...
[WARNING]: 2023-03-14 13:19:10 - status code: 502
[ERROR]: 2023-03-14 13:19:10 - a4k GetMixMediaInfo SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:10 - Queue 1 a4k End...
[ERROR]: 2023-03-14 13:19:10 - Queue 1 a4k oneMovieDlSubInOneSite SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:10 - Queue 1 assrt /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:10 - Queue 1 assrt Start...
[WARNING]: 2023-03-14 13:19:11 - status code: 502
[ERROR]: 2023-03-14 13:19:11 - assrt /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv GetMixMediaInfo SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:11 - Queue 1 assrt End...
[ERROR]: 2023-03-14 13:19:11 - Queue 1 assrt oneMovieDlSubInOneSite SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:11 - Queue 1 DlSub End /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[WARNING]: 2023-03-14 13:19:11 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2023-03-14 13:19:11 - No Sub Found 钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:24 - ------------------------------------------
[INFO]: 2023-03-14 13:19:24 - OneTimeSubtitleScanStart#50c0d6e973b1959196fcf92760f511cc74424d990609439719964dc921c49b78
[WARNING]: 2023-03-14 13:19:24 - cancel Downloader.QueueDownloader()
[INFO]: 2023-03-14 13:19:24 - Queue 1 DlSub Start /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:24 - OneTimeSubtitleScanEnd
[INFO]: 2023-03-14 13:19:24 - Queue 1 xunlei /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:24 - Queue 1 xunlei Start...
[INFO]: 2023-03-14 13:19:24 - ------------------------------------------
[INFO]: 2023-03-14 13:19:24 - Queue 1 xunlei End...
[INFO]: 2023-03-14 13:19:24 - Queue 1 shooter /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:24 - Queue 1 shooter Start...
[INFO]: 2023-03-14 13:19:25 - Queue 1 shooter End...
[INFO]: 2023-03-14 13:19:25 - Queue 1 a4k /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:25 - Queue 1 a4k Start...
[WARNING]: 2023-03-14 13:19:25 - status code: 502
[ERROR]: 2023-03-14 13:19:25 - a4k GetMixMediaInfo SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:25 - Queue 1 a4k End...
[ERROR]: 2023-03-14 13:19:25 - Queue 1 a4k oneMovieDlSubInOneSite SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:25 - Queue 1 assrt /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[INFO]: 2023-03-14 13:19:25 - Queue 1 assrt Start...
[WARNING]: 2023-03-14 13:19:26 - status code: 502
[ERROR]: 2023-03-14 13:19:26 - assrt /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv GetMixMediaInfo SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:26 - Queue 1 assrt End...
[ERROR]: 2023-03-14 13:19:26 - Queue 1 assrt oneMovieDlSubInOneSite SubtitleBestApi.GetMediaInfo failed, Message:
[INFO]: 2023-03-14 13:19:26 - Queue 1 DlSub End /media/movies/钢铁侠 (2008)/钢铁侠 (2008) - 1080p.mkv
[WARNING]: 2023-03-14 13:19:26 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2023-03-14 13:19:26 - No Sub Found 钢铁侠 (2008) - 1080p.mkv

**Comment by allanpk716** [comment]
用自己的 TMDB API

**Comment by songzijiang** [comment]
> 用自己的 TMDB API

建议加入api.tmdb.org的TMDB接口。能解决几乎90%人的网络问题。还有目前代理的逻辑没看懂，本地端口的设置是什么意思。curl时我的代理可以用，curl的命令行如下：curl -x socks5h://127.0.0.1:1080 www.google.com 但是csf中我自己的代理一直连不上，不知道问题出在哪。

**Comment by songzijiang** [comment]
> 

我配置了 extra_hosts:，但是TMDB依旧连不上

**Comment by songzijiang** [comment]
另外，我的刮削文件里面已经有了tmdb和imdb号，能否使用nfo刮削文件里的数据，而不是重新查询tmdb。nfo是利用nastool刮削出来的。

**Comment by allanpk716** [comment]
有 issue 提过这个链接 api.tmdb.org 问题，看对应的讨论，现在能用不代表以后能用，也不代表所有国内的网络都能用，新增的意义不大。 #607

今天是云服务故障，刚有空去排查。

**Comment by allanpk716** [comment]
升级最新
