### ISSUE TITLE
无法搜索字幕

### ISSUE THREAD

**Issue by lucifer-j** [ChineseSubFinder/ChineseSubFinder#633]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
>v0.47.4
> 环境: docker or Window or Linux or MAC
>docker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？
无法搜索字幕

![image](https://user-images.githubusercontent.com/4360479/225267375-2f4c5064-8264-48e6-b401-822deba3612e.png)

## 你的问题弄重现嘛？

> 能够重现
## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "SpeedDevMode": false,
    "user_info": {
        "username": "xxx",
        "password": "xxx"
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 3,
        "run_scan_at_start_up": false,
        "movie_paths": [
            "/media/link/Movies",
            "/media/link/18R-film"
        ],
        "series_paths": [
            "/media/link/Series",
            "/media/link/18R-TV"
        ],
        "local_static_file_port": "19037"
    },
    "subtitle_sources": {
        "assrt_settings": {
            "enabled": false,
            "token": ""
        },
        "subtitle_best_settings": {
            "enabled": false,
            "api_key": ""
        }
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_proxy": false,
            "use_which_proxy_protocol": "http",
            "local_http_proxy_server_port": "19036",
            "input_proxy_address": "127.0.0.1",
            "input_proxy_port": "10809",
            "need_pwd": false,
            "input_proxy_username": "",
            "input_proxy_password": ""
        },
        "tmdb_api_settings": {
            "enable": true,
            "api_key": "xxx"
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 1,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": true,
        "topic": 1,
        "suppliers_settings": {
            "xunlei": {
                "name": "xunlei",
                "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "search_url": "",
                "daily_download_limit": -1
            },
            "shooter": {
                "name": "shooter",
                "root_url": "https://www.shooter.cn/api/subapi.php",
                "search_url": "",
                "daily_download_limit": -1
            },
            "assrt": {
                "name": "assrt",
                "root_url": "https://api.assrt.net/v1",
                "search_url": "",
                "daily_download_limit": -1
            },
            "a4k": {
                "name": "a4k",
                "root_url": "https://www.a4k.net",
                "search_url": "/search?term=",
                "daily_download_limit": -1
            },
            "subhd": {
                "name": "subhd",
                "root_url": "https://subhd.tv",
                "search_url": "/search/%s",
                "daily_download_limit": 20
            },
            "zimuku": {
                "name": "zimuku",
                "root_url": "https://zimuku.org",
                "search_url": "/search?q=%s",
                "daily_download_limit": 20
            }
        },
        "scan_logic": {
            "skip_chinese_movie": true,
            "skip_chinese_series": true
        },
        "task_queue": {
            "max_retry_times": 3,
            "one_job_time_out": 300,
            "interval": 10,
            "expiration_time": 90,
            "download_sub_during_x_days": 7,
            "one_sub_download_interval": 12,
            "check_pulic_ip_target_site": ""
        },
        "download_file_cache": {
            "ttl": 4320,
            "unit": "hour"
        }
    },
    "emby_settings": {
        "enable": false,
        "address_url": "",
        "api_key": "",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/link/18R-film": "",
            "/media/link/Movies": ""
        },
        "series_paths_mapping": {
            "/media/link/18R-TV": "",
            "/media/link/Series": ""
        },
        "auto_or_manual": true,
        "threads": 3
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 700,
        "min_offset": 0.2
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        },
        "api_key_settings": {
            "enabled": true,
            "key": "xxx"
        },
        "local_chrome_settings": {
            "enabled": false,
            "local_chrome_exe_f_path": ""
        },
        "share_sub_settings": {
            "share_sub_enabled": false
        },
        "extend_log": {
            "SysLog": {
                "enable": false,
                "network": "",
                "address": "",
                "priority": 0,
                "tag": ""
            }
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /mnt/user/appdata/chinesesubfinder/config:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mnt/user/Unraid_video:/media    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - ./browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=99           # uid
      - PGID=100          # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    restart: always
    network_mode: bridge
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035  # 从0.20.0版本开始，通过webui来设置
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整
    extra_hosts:
      - api.themoviedb.org:18.66.97.86
      - api.themoviedb.org:18.66.97.35
      - api.themoviedb.org:18.66.97.54
      - api.themoviedb.org:18.66.97.105
      - api.themoviedb.org:2600:9000:223c:a200:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:9a00:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:7800:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:8000:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:f000:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:9000:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:3800:10:fb02:4000:93a1
      - api.themoviedb.org:2600:9000:223c:4c00:10:fb02:4000:93a1

## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

已设置 PERMS=true，重设 '/media' 目录权限为 99:100 所有...
[INFO]: 2023-03-15 17:27:52 - LiteMode is true
[INFO]: 2023-03-15 17:27:52 - ChineseSubFinder Version: v0.47.4 Lite

[INFO]: 2023-03-15 17:27:52 - Reload Log Settings, level = Info
[INFO]: 2023-03-15 17:27:52 - Speed Dev Mode is Off
[INFO]: 2023-03-15 17:27:52 - PreJob.HotFix() Start...
[INFO]: 2023-03-15 17:27:52 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-03-15 17:27:52 - PreJob.HotFix() End
[INFO]: 2023-03-15 17:27:52 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2023-03-15 17:27:52 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-03-15 17:27:52 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2023-03-15 17:27:52 - PreJob.ChangeSubNameFormat() End
[INFO]: 2023-03-15 17:27:52 - PreJob.Wait() Done.
[INFO]: 2023-03-15 17:27:52 - ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers

built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r3) 20220924
configuration: --prefix=/usr --enable-avfilter --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --disable-lzma --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --enable-libzmq --optflags=-O2 --disable-debug --enable-libsvtav1
libavutil 57. 28.100 / 57. 28.100
libavcodec 59. 37.100 / 59. 37.100
libavformat 59. 27.100 / 59. 27.100
libavdevice 59. 7.100 / 59. 7.100
libavfilter 8. 44.100 / 8. 44.100
libswscale 6. 7.100 / 6. 7.100
libswresample 4. 7.100 / 4. 7.100
libpostproc 56. 6.100 / 56. 6.100

ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers

built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r3) 20220924
configuration: --prefix=/usr --enable-avfilter --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --disable-lzma --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --enable-libzmq --optflags=-O2 --disable-debug --enable-libsvtav1
libavutil 57. 28.100 / 57. 28.100
libavcodec 59. 37.100 / 59. 37.100
libavformat 59. 27.100 / 59. 27.100
libavdevice 59. 7.100 / 59. 7.100
libavfilter 8. 44.100 / 8. 44.100
libswscale 6. 7.100 / 6. 7.100
libswresample 4. 7.100 / 4. 7.100
libpostproc 56. 6.100 / 56. 6.100

[INFO]: 2023-03-15 17:27:52 - Download.SupplierCheck() Start ...
[INFO]: 2023-03-15 17:27:52 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-03-15 17:27:52 - PreDownloadProcess.Init() Start...
[INFO]: 2023-03-15 17:27:52 - ClearRodTmpRootFolder Done
[INFO]: 2023-03-15 17:27:52 - PreDownloadProcess.Init() End
[INFO]: 2023-03-15 17:27:52 - PreDownloadProcess.Check() Start...
[INFO]: 2023-03-15 17:27:52 - UseHttpProxy = false
[ERROR]: 2023-03-15 17:27:57 - UrlConnectednessTest Target Site https://baidu.com, Get "https://baidu.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[INFO]: 2023-03-15 17:27:57 - Check Sub Supplier Start...
[ERROR]: 2023-03-15 17:27:57 - UrlConnectednessTest Target Site https://baidu.com, Get "https://baidu.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[INFO]: 2023-03-15 17:27:57 - Check Sub Supplier Start...
2023/03/15 17:28:57.397816 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/FB4E2AFF106112136DFC5ACC7339EB29D1EC0CF8.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1

2023/03/15 17:29:57.499359 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/FB4E2AFF106112136DFC5ACC7339EB29D1EC0CF8.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2

[ERROR]: 2023-03-15 17:29:57 - xunlei NewHttpClient: CheckFileName Get "http://sub.xmp.sandai.net:8000/subxl/FB4E2AFF106112136DFC5ACC7339EB29D1EC0CF8.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[ERROR]: 2023-03-15 17:29:57 - xunlei CheckAlive Error Get "http://sub.xmp.sandai.net:8000/subxl/FB4E2AFF106112136DFC5ACC7339EB29D1EC0CF8.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[WARNING]: 2023-03-15 17:29:57 - xunlei Check Alive = false

[INFO]: 2023-03-15 17:29:58 - shooter Check Alive = true, Speed = 774 ms
[INFO]: 2023-03-15 17:29:58 - shooter Check Alive = true, Speed = 774 ms
[INFO]: 2023-03-15 17:29:58 - a4k Check Alive = true, Speed = 530 ms
[INFO]: 2023-03-15 17:29:58 - Alive Supplier: shooter
[INFO]: 2023-03-15 17:29:58 - Alive Supplier: a4k
[INFO]: 2023-03-15 17:29:58 - Check Sub Supplier End
[INFO]: 2023-03-15 17:29:58 - MovieFolder Index 0 -- /media/link/Movies
[INFO]: 2023-03-15 17:29:58 - MovieFolder Index 1 -- /media/link/18R-film
[INFO]: 2023-03-15 17:29:58 - SeriesPaths Index 0 -- /media/link/Series
[INFO]: 2023-03-15 17:29:58 - SeriesPaths Index 1 -- /media/link/18R-TV
[INFO]: 2023-03-15 17:29:58 - PreDownloadProcess.Check() End
[INFO]: 2023-03-15 17:29:58 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-03-15 17:29:58 - Download.SupplierCheck() End
[INFO]: 2023-03-15 17:29:58 - Setup is Done
[INFO]: 2023-03-15 17:29:58 - RunAtStartup: false, so will not Run At Startup
[INFO]: 2023-03-15 17:29:58 - CronHelper Start...
[INFO]: 2023-03-15 17:29:58 - Next Sub Scan Will Process At: 2023-03-15 23:29:58
[ERROR]: 2023-03-15 17:29:58 - GetSearchMulti Get "https://api.themoviedb.org/3/search/multi?api_key=023813add071537d609e7a286d530ff7&query=Dexter&language=en-US": dial tcp [2600:9000:223c:4c00:10:fb02:4000:93a1]:443: connect: cannot assign requested address

[ERROR]: 2023-03-15 17:29:58 - tmdbApi.Alive() == false

[INFO]: 2023-03-15 17:29:58 - Try Start Http Server At Port 19035
[WARNING]: 2023-03-15 17:31:09 - getSubListFromFile /media/link/18R-film/外语电影/抓住稻草的野兽 (2020)/抓住稻草的野兽 (2020) - 1080p.mkv no metadata file, movie.xml or *.nfo

[ERROR]: 2023-03-15 17:31:09 - PreviewVideoFPath2IMDBInfo no metadata file, movie.xml or *.nfo

[WARNING]: 2023-03-15 17:31:12 - getSubListFromFile /media/link/18R-film/外语电影/抓住稻草的野兽 (2020)/抓住稻草的野兽 (2020) - 1080p.mkv no metadata file, movie.xml or *.nfo

[ERROR]: 2023-03-15 17:31:12 - PreviewVideoFPath2IMDBInfo no metadata file, movie.xml or *.nfo

[WARNING]: 2023-03-15 17:31:12 - getSubListFromFile /media/link/18R-film/外语电影/抓住稻草的野兽 (2020)/抓住稻草的野兽 (2020) - 1080p.mkv no metadata file, movie.xml or *.nfo

[ERROR]: 2023-03-15 17:31:12 - PreviewVideoFPath2IMDBInfo no metadata file, movie.xml or *.nfo

[WARNING]: 2023-03-15 17:31:48 - getSubListFromFile /media/link/18R-film/外语电影/抓住稻草的野兽 (2020)/抓住稻草的野兽 (2020) - 1080p.mkv no metadata file, movie.xml or *.nfo

[ERROR]: 2023-03-15 17:31:48 - PreviewVideoFPath2IMDBInfo no metadata file, movie.xml or *.nfo

**Comment by allanpk716** [comment]
配置 TMDB API ，有“测试”按钮，自己配合代理使用

**Comment by lucifer-j** [comment]
> 配置 TMDB API ，有“测试”按钮，自己配合代理使用
去掉了这些
extra_hosts:
- api.themoviedb.org:18.66.97.86
- api.themoviedb.org:18.66.97.35
- api.themoviedb.org:18.66.97.54
- api.themoviedb.org:18.66.97.105
- api.themoviedb.org:2600:9000:223c:a200:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:9a00:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:7800:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:8000:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:f000:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:9000:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:3800:10:fb02:4000:93a1
- api.themoviedb.org:2600:9000:223c:4c00:10:fb02:4000:93a1

然后挂了代理，API检查是正常，但是还是无法搜索
![image](https://user-images.githubusercontent.com/4360479/225273524-afb5ad51-78aa-48fb-8c41-3c6a56e86fb3.png)
![image](https://user-images.githubusercontent.com/4360479/225273622-d9cbdbd8-825f-4b06-9854-bf87385d27b2.png)

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/225529391-28457022-3af9-44ca-8550-9592c926fa3e.png)

削刮？

**Comment by lucifer-j** [comment]
> ![image](https://user-images.githubusercontent.com/1176000/225529391-28457022-3af9-44ca-8550-9592c926fa3e.png)
> 
> 削刮？

是要先刮削nfo再搜索？

**Comment by baiyefeiyu** [comment]
一模一样的问题，你解决了么

**Comment by baiyefeiyu** [comment]
![image](https://user-images.githubusercontent.com/112963200/231821680-2290d59b-93e3-4f47-9162-197a9f0f1138.png)

**Comment by baiyefeiyu** [comment]
我刮削过了，群晖配置了hosts，nastools同样的tmdb api没问题

**Comment by allanpk716** [comment]
升级最新
