### ISSUE TITLE
请修改相关配置后继续 

### ISSUE THREAD

**Issue by paysenyu** [ChineseSubFinder/ChineseSubFinder#638]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.48.0
>
> 环境: docker 
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

请修改相关配置后继续 

<img width="307" alt="709cbf9fee722025612e7a300b55d84" src="https://user-images.githubusercontent.com/51367628/226358251-24c6a134-ea4b-42ef-b146-f31de60a703a.png">

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

因为我有3个盘，所以docker 的yml配置如下

      - /volume2/Media2:/Media2
      - /volume1/Media1:/Media1
      - /volume3/Media3:/Media3 
     
应用中的设置如图

![image](https://user-images.githubusercontent.com/51367628/226358976-9d0a39b1-9c53-432a-9514-0e7ff6507baa.png)

这个配置在emby，transmission 均为正确配置。 

在早期的版本也同样正常运作，今天更新0.48.0 之后弹出此提示，其他设置均无法保存。

**Comment by allanpk716** [comment]
映射到容器内的目录名称提示上写了: /media

/media/Media1
/media/Media2
/media/Media3

以此类推

**Comment by paysenyu** [comment]
> 

<img width="221" alt="image" src="https://user-images.githubusercontent.com/51367628/226497657-9f83cce6-a390-4321-ab56-1c9c91615ff0.png">


我是需要先把这里修改了吗？ 
  - /volume2/Media2:/media/Media2
  - /volume1/Media1:/media/Media1
  - /volume3/Media3:/media/Media3

**Comment by paysenyu** [comment]
/volume2/Media2:/media/Media2
/volume1/Media1:/media/Media1
/volume3/Media3:/media/Media3

已经修正成这样，目前暂时未发现异常。
