### ISSUE TITLE
上传字幕速度太慢。

### ISSUE THREAD

**Issue by zraxx** [ChineseSubFinder/ChineseSubFinder#641]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.50.0

环境: docker 

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？
上传单个字幕慢，上传整季字幕更慢，只能打开媒体服务库直接上传，能否改进！谢谢！
## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
关闭字幕时间轴矫正

**Comment by zraxx** [comment]
> 关闭字幕时间轴矫正

ok
