### ISSUE TITLE
手动搜索字幕，出现网络错误的情况

### ISSUE THREAD

**Issue by wannantian** [ChineseSubFinder/ChineseSubFinder#646]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.50.0 Lite
>
> 环境: docker 和群晖套件均出现该问题
>
问题 ：手动搜索字幕出现网络错误。**附件是日志**
[ChineseSubFinder.log](https://github.com/ChineseSubFinder/ChineseSubFinder/files/11145489/ChineseSubFinder.log)

**下列代码是手动搜索报错后的日志。**
[31m2023/04/04 11:42:29 [Recovery] 2023/04/04 - 11:42:29 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:221 (0x44e255)
/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:735 (0x44e225)
/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/settings/supplier_settings.go:39 (0xeb9df3)
/home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/backend/controllers/v1/preview.go:185 (0xeb9ddb)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xec0056)
/home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/backend/middle/auth.go:30 (0xebff4c)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xe913e1)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101 (0xe913cc)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xe90606)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/logger.go:240 (0xe905e9)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173 (0xe8fb50)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616 (0xe8f7b8)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572 (0xe8f2fc)
/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:2879 (0x6e47fa)
/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/server.go:1930 (0x6dfea7)
/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581 (0x469ba0)

**Comment by Toylee2019** [comment]
同上

**Comment by wannantian** [comment]
更新到50.3 但是依旧没有修复这个问题。附件是日志

**Comment by wannantian** [comment]
更新到50.3 但是依旧没有修复这个问题。附件是日志
[ChineseSubFinder.log](https://github.com/ChineseSubFinder/ChineseSubFinder/files/11182635/ChineseSubFinder.log)
