### ISSUE TITLE
pull的是 latest 但主页上显示的是 lite，连续剧字幕无法批量下载

### ISSUE THREAD

**Issue by Neo-AK** [ChineseSubFinder/ChineseSubFinder#653]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

 chinesesubfinder 版本: v0.50.4 (Lite)

环境: docker

[INFO]: 2023-04-15 10:32:14 - LiteMode is true
[INFO]: 2023-04-15 10:32:14 - ChineseSubFinder Version: v0.50.4 Lite
[INFO]: 2023-04-15 10:32:14 - Reload Log Settings, level = Info
[INFO]: 2023-04-15 10:32:14 - Speed Dev Mode is Off
[INFO]: 2023-04-15 10:32:14 - PreJob.HotFix() Start...
[INFO]: 2023-04-15 10:32:14 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-04-15 10:32:14 - PreJob.HotFix() End
[INFO]: 2023-04-15 10:32:14 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2023-04-15 10:32:14 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-04-15 10:32:14 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2023-04-15 10:32:14 - PreJob.ChangeSubNameFormat() End
[INFO]: 2023-04-15 10:32:14 - PreJob.Wait() Done.
[INFO]: 2023-04-15 10:32:14 - Download.SupplierCheck() Start ...
[INFO]: 2023-04-15 10:32:14 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-04-15 10:32:14 - PreDownloadProcess.Init() Start...
[INFO]: 2023-04-15 10:32:14 - ClearRodTmpRootFolder Done
[INFO]: 2023-04-15 10:32:14 - PreDownloadProcess.Init() End
[INFO]: 2023-04-15 10:32:14 - PreDownloadProcess.Check() Start...
[INFO]: 2023-04-15 10:32:14 - UseHttpProxy = false
[INFO]: 2023-04-15 10:32:15 - UrlConnectednessTest Target Site https://baidu.com Speed: 154 ms, Status: true
[INFO]: 2023-04-15 10:32:15 - Check Sub Supplier Start...
[INFO]: 2023-04-15 10:32:15 - xunlei Check Alive = true, Speed = 41 ms
[INFO]: 2023-04-15 10:32:17 - shooter Check Alive = true, Speed = 2442 ms
[INFO]: 2023-04-15 10:32:18 - a4k Check Alive = true, Speed = 738 ms
[INFO]: 2023-04-15 10:32:18 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 4
[INFO]: 2023-04-15 10:32:18 - assrt Check Alive = true, Speed = 454 ms
[INFO]: 2023-04-15 10:32:19 - subtitle_best Check Alive = true, Speed = 760 ms
[INFO]: 2023-04-15 10:32:19 - Alive Supplier: xunlei
[INFO]: 2023-04-15 10:32:19 - Alive Supplier: shooter
[INFO]: 2023-04-15 10:32:19 - Alive Supplier: a4k
[INFO]: 2023-04-15 10:32:19 - Alive Supplier: assrt
[INFO]: 2023-04-15 10:32:19 - Alive Supplier: subtitle_best
[INFO]: 2023-04-15 10:32:19 - Check Sub Supplier End
[INFO]: 2023-04-15 10:32:19 - MovieFolder Index 0 -- /media/movies
[INFO]: 2023-04-15 10:32:19 - SeriesPaths Index 0 -- /media/series
[INFO]: 2023-04-15 10:32:19 - PreDownloadProcess.Check() End
[INFO]: 2023-04-15 10:32:19 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-04-15 10:32:19 - Download.SupplierCheck() End
[INFO]: 2023-04-15 10:32:19 - Setup is Done
[INFO]: 2023-04-15 10:32:19 - RunAtStartup: false, so will not Run At Startup
[INFO]: 2023-04-15 10:32:19 - CronHelper Start...
[INFO]: 2023-04-15 10:32:19 - Try Start Http Server At Port 19035
[INFO]: 2023-04-15 10:32:19 - Next Sub Scan Will Process At: 2023-04-15 16:32:19

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/129709170/232194032-1ece0574-8a7f-4c15-92a1-03049562a016.png)

1. 我pull的是 allanpk716/chinesesubfinder:latest 但是为何启动的是 lite？
2. 可以扫描到库中的电影和连续剧，点电影海报下的下载小图标可以排进下载队列，类似点开连续剧的添加到下载队列则无任何反应。如果点放大镜搜索则可以搜到并下载成功。我检查了连续剧文件夹，里面确定有tvshow.nfo和每集的nfo。
3. 下载队列没有自动运行，在总览里守护进程显示是“运行中”。
4. 总览界面很空白除了可以点击强制停止没有其他log显示，我好像看到别人的教程里这个界面有个打印框，不知道这个版本是不是没有？

## 你的问题能重现嘛？

能够重现

## 你期望的结果

能工扫描媒体库后自动下载确实的中文字幕

## 给出当前程序的配置文件

```json
{
    "SpeedDevMode": false,
    "user_info": {
        "username": "",
        "password": ""
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 3,
        "run_scan_at_start_up": false,
        "movie_paths": [
            "/media/movies"
        ],
        "series_paths": [
            "/media/series"
        ],
        "local_static_file_port": "19037"
    },
    "subtitle_sources": {
        "assrt_settings": {
            "enabled": true,
            "token": "xxxx"
        },
        "subtitle_best_settings": {
            "enabled": true,
            "api_key": "xxxx"
        }
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_proxy": false,
            "use_which_proxy_protocol": "socks5",
            "local_http_proxy_server_port": "19036",
            "input_proxy_address": "xxxx",
            "input_proxy_port": "000",
            "need_pwd": false,
            "input_proxy_username": "",
            "input_proxy_password": ""
        },
        "tmdb_api_settings": {
            "enable": false,
            "api_key": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 0,
        "save_multi_sub": true,
        "custom_video_exts": [],
        "fix_time_line": false,
        "topic": 1,
        "suppliers_settings": {
            "xunlei": {
                "name": "xunlei",
                "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "search_url": "",
                "daily_download_limit": -1
            },
            "shooter": {
                "name": "shooter",
                "root_url": "https://www.shooter.cn/api/subapi.php",
                "search_url": "",
                "daily_download_limit": -1
            },
            "assrt": {
                "name": "assrt",
                "root_url": "https://api.assrt.net/v1",
                "search_url": "",
                "daily_download_limit": -1
            },
            "a4k": {
                "name": "a4k",
                "root_url": "https://www.a4k.net",
                "search_url": "/search?term=",
                "daily_download_limit": -1
            },
            "subhd": {
                "name": "subhd",
                "root_url": "https://subhd.tv",
                "search_url": "/search/%s",
                "daily_download_limit": 20
            },
            "zimuku": {
                "name": "zimuku",
                "root_url": "https://zimuku.org",
                "search_url": "/search?q=%s",
                "daily_download_limit": 20
            },
            "subtitle_best": {
                "name": "subtitle_best",
                "root_url": "https://api.subtitle.best/share-sub/v1",
                "search_url": "/search-movie",
                "daily_download_limit": -1
            }
        },
        "scan_logic": {
            "skip_chinese_movie": false,
            "skip_chinese_series": false
        },
        "task_queue": {
            "max_retry_times": 3,
            "one_job_time_out": 300,
            "interval": 10,
            "expiration_time": 90,
            "download_sub_during_x_days": 7,
            "one_sub_download_interval": 12,
            "check_pulic_ip_target_site": ""
        },
        "download_file_cache": {
            "ttl": 4320,
            "unit": "hour"
        }
    },
    "emby_settings": {
        "enable": true,
        "address_url": "http://xxxx:8096",
        "api_key": "xxxx",
        "max_request_video_number": 3000,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/movies": ""
        },
        "series_paths_mapping": {
            "/media/series": ""
        },
        "auto_or_manual": true,
        "threads": 3
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 700,
        "min_offset": 0.2
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        },
        "api_key_settings": {
            "enabled": true,
            "key": "xxxx"
        },
        "local_chrome_settings": {
            "enabled": false,
            "local_chrome_exe_f_path": ""
        },
        "share_sub_settings": {
            "share_sub_enabled": false
        },
        "extend_log": {
            "SysLog": {
                "enable": false,
                "network": "",
                "address": "",
                "priority": 0,
                "tag": ""
            }
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

docker run -d \
  -v /share/Container/chinesesubfinder/config:/config \
  -v /share/xxx/media:/media \
  -v /share/Container/chinesesubfinder/browser:/root/.cache/rod/browser \
  -e PUID=1000 \
  -e PGID=100 \
  -e PERMS=true \
  -e TZ=Asia/Shanghai \
  -e UMASK=022 \
  -p 19035:19035 \
  -p 19037:19037 \
  --name chinesesubfinder \
  --hostname chinesesubfinder \
  --log-driver "json-file" \
  --log-opt "max-size=100m" \
  allanpk716/chinesesubfinder:latest

## 给出媒体文件夹的目录结构

![image](https://user-images.githubusercontent.com/129709170/232193798-c9513120-5a0b-450d-877c-34b15fcfc811.png)

- [电影的推荐目录结构](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/ChineseSubFinder/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

[INFO]: 2023-04-15 11:32:19 - PreDownloadProcess.Init() End
[INFO]: 2023-04-15 11:32:19 - PreDownloadProcess.Check() Start...
[INFO]: 2023-04-15 11:32:19 - UseHttpProxy = false
[INFO]: 2023-04-15 11:32:19 - UrlConnectednessTest Target Site https://baidu.com Speed: 200 ms, Status: true
[INFO]: 2023-04-15 11:32:19 - Check Sub Supplier Start...
[INFO]: 2023-04-15 11:32:19 - xunlei Check Alive = true, Speed = 39 ms
[INFO]: 2023-04-15 11:32:20 - shooter Check Alive = true, Speed = 912 ms
[INFO]: 2023-04-15 11:32:20 - a4k Check Alive = true, Speed = 824 ms
[INFO]: 2023-04-15 11:32:21 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 4
[INFO]: 2023-04-15 11:32:21 - assrt Check Alive = true, Speed = 306 ms
[INFO]: 2023-04-15 11:32:22 - subtitle_best Check Alive = true, Speed = 727 ms
[INFO]: 2023-04-15 11:32:22 - Alive Supplier: xunlei
[INFO]: 2023-04-15 11:32:22 - Alive Supplier: shooter
[INFO]: 2023-04-15 11:32:22 - Alive Supplier: a4k
[INFO]: 2023-04-15 11:32:22 - Alive Supplier: assrt
[INFO]: 2023-04-15 11:32:22 - Alive Supplier: subtitle_best
[INFO]: 2023-04-15 11:32:22 - Check Sub Supplier End
[INFO]: 2023-04-15 11:32:22 - MovieFolder Index 0 -- /media/movies
[INFO]: 2023-04-15 11:32:22 - SeriesPaths Index 0 -- /media/series
[INFO]: 2023-04-15 11:32:22 - PreDownloadProcess.Check() End
[INFO]: 2023-04-15 11:32:22 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-04-15 11:32:22 - Download.SupplierCheck() End
[INFO]: 2023-04-15 12:32:19 - Download.SupplierCheck() Start ...
[INFO]: 2023-04-15 12:32:19 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-04-15 12:32:19 - PreDownloadProcess.Init() Start...
[INFO]: 2023-04-15 12:32:19 - ClearRodTmpRootFolder Done
[INFO]: 2023-04-15 12:32:19 - PreDownloadProcess.Init() End
[INFO]: 2023-04-15 12:32:19 - PreDownloadProcess.Check() Start...
[INFO]: 2023-04-15 12:32:19 - UseHttpProxy = false
[INFO]: 2023-04-15 12:32:19 - UrlConnectednessTest Target Site https://baidu.com Speed: 145 ms, Status: true
[INFO]: 2023-04-15 12:32:19 - Check Sub Supplier Start...
[INFO]: 2023-04-15 12:32:19 - xunlei Check Alive = true, Speed = 40 ms
[INFO]: 2023-04-15 12:32:22 - shooter Check Alive = true, Speed = 3292 ms
[INFO]: 2023-04-15 12:32:23 - a4k Check Alive = true, Speed = 923 ms
[INFO]: 2023-04-15 12:32:24 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 4
[INFO]: 2023-04-15 12:32:24 - assrt Check Alive = true, Speed = 678 ms
[INFO]: 2023-04-15 12:32:24 - subtitle_best Check Alive = true, Speed = 752 ms
[INFO]: 2023-04-15 12:32:24 - Alive Supplier: xunlei
[INFO]: 2023-04-15 12:32:24 - Alive Supplier: shooter
[INFO]: 2023-04-15 12:32:24 - Alive Supplier: a4k
[INFO]: 2023-04-15 12:32:24 - Alive Supplier: assrt
[INFO]: 2023-04-15 12:32:24 - Alive Supplier: subtitle_best
[INFO]: 2023-04-15 12:32:24 - Check Sub Supplier End
[INFO]: 2023-04-15 12:32:24 - MovieFolder Index 0 -- /media/movies
[INFO]: 2023-04-15 12:32:24 - SeriesPaths Index 0 -- /media/series
[INFO]: 2023-04-15 12:32:24 - PreDownloadProcess.Check() End
[INFO]: 2023-04-15 12:32:24 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-04-15 12:32:24 - Download.SupplierCheck() End
[INFO]: 2023-04-15 13:32:19 - Download.SupplierCheck() Start ...
[INFO]: 2023-04-15 13:32:19 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-04-15 13:32:19 - PreDownloadProcess.Init() Start...
[INFO]: 2023-04-15 13:32:19 - ClearRodTmpRootFolder Done
[INFO]: 2023-04-15 13:32:19 - PreDownloadProcess.Init() End
[INFO]: 2023-04-15 13:32:19 - PreDownloadProcess.Check() Start...
[INFO]: 2023-04-15 13:32:19 - UseHttpProxy = false
[INFO]: 2023-04-15 13:32:19 - UrlConnectednessTest Target Site https://baidu.com Speed: 141 ms, Status: true
[INFO]: 2023-04-15 13:32:19 - Check Sub Supplier Start...
[INFO]: 2023-04-15 13:32:19 - xunlei Check Alive = true, Speed = 52 ms
[INFO]: 2023-04-15 13:32:19 - shooter Check Alive = true, Speed = 498 ms
[INFO]: 2023-04-15 13:32:20 - a4k Check Alive = true, Speed = 927 ms
[INFO]: 2023-04-15 13:32:20 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 5
[INFO]: 2023-04-15 13:32:20 - assrt Check Alive = true, Speed = 297 ms
[INFO]: 2023-04-15 13:32:21 - subtitle_best Check Alive = true, Speed = 790 ms
[INFO]: 2023-04-15 13:32:21 - Alive Supplier: xunlei
[INFO]: 2023-04-15 13:32:21 - Alive Supplier: shooter
[INFO]: 2023-04-15 13:32:21 - Alive Supplier: a4k
[INFO]: 2023-04-15 13:32:21 - Alive Supplier: assrt
[INFO]: 2023-04-15 13:32:21 - Alive Supplier: subtitle_best
[INFO]: 2023-04-15 13:32:21 - Check Sub Supplier End
[INFO]: 2023-04-15 13:32:21 - MovieFolder Index 0 -- /media/movies
[INFO]: 2023-04-15 13:32:21 - SeriesPaths Index 0 -- /media/series
[INFO]: 2023-04-15 13:32:21 - PreDownloadProcess.Check() End
[INFO]: 2023-04-15 13:32:21 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-04-15 13:32:21 - Download.SupplierCheck() End
[INFO]: 2023-04-15 14:32:19 - Download.SupplierCheck() Start ...
[INFO]: 2023-04-15 14:32:19 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-04-15 14:32:19 - PreDownloadProcess.Init() Start...
[INFO]: 2023-04-15 14:32:19 - ClearRodTmpRootFolder Done
[INFO]: 2023-04-15 14:32:19 - PreDownloadProcess.Init() End
[INFO]: 2023-04-15 14:32:19 - PreDownloadProcess.Check() Start...
[INFO]: 2023-04-15 14:32:19 - UseHttpProxy = false
[INFO]: 2023-04-15 14:32:19 - UrlConnectednessTest Target Site https://baidu.com Speed: 152 ms, Status: true
[INFO]: 2023-04-15 14:32:19 - Check Sub Supplier Start...
[INFO]: 2023-04-15 14:32:19 - xunlei Check Alive = true, Speed = 195 ms
[INFO]: 2023-04-15 14:32:23 - shooter Check Alive = true, Speed = 4381 ms
[INFO]: 2023-04-15 14:32:24 - a4k Check Alive = true, Speed = 1148 ms
[INFO]: 2023-04-15 14:32:25 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 4
[INFO]: 2023-04-15 14:32:25 - assrt Check Alive = true, Speed = 312 ms
[INFO]: 2023-04-15 14:32:25 - subtitle_best Check Alive = true, Speed = 736 ms
[INFO]: 2023-04-15 14:32:25 - Alive Supplier: xunlei
[INFO]: 2023-04-15 14:32:25 - Alive Supplier: shooter
[INFO]: 2023-04-15 14:32:25 - Alive Supplier: a4k
[INFO]: 2023-04-15 14:32:25 - Alive Supplier: assrt
[INFO]: 2023-04-15 14:32:25 - Alive Supplier: subtitle_best
[INFO]: 2023-04-15 14:32:25 - Check Sub Supplier End
[INFO]: 2023-04-15 14:32:25 - MovieFolder Index 0 -- /media/movies
[INFO]: 2023-04-15 14:32:25 - SeriesPaths Index 0 -- /media/series
[INFO]: 2023-04-15 14:32:25 - PreDownloadProcess.Check() End
[INFO]: 2023-04-15 14:32:25 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-04-15 14:32:25 - Download.SupplierCheck() End

**Comment by allanpk716** [comment]
1. 看项目首页，有说；
2. 连续剧目录结构不对，一样，看首页要求；
3. 守护进程开着就行了
4. 不要看过期的教程，看首页的；
