### ISSUE TITLE
希望提供一个与视频文件名相同的字幕文件

### ISSUE THREAD

**Issue by wzsxy** [ChineseSubFinder/ChineseSubFinder#660]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker 

## 你想要新增或者改进什么功能？

希望提供一个与视频文件名相同的字幕文件，因为一些蓝光机如OPPO在读取外挂字幕时，只会读取名称与视频文件名称完全相同的字幕，这就意味着任何后缀如en, zh, chs将会导致字幕无挂载

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
这两天会发布，你去进阶设置去修改，大概选项命名是：


![image](https://user-images.githubusercontent.com/1176000/233962267-3e17e13a-c568-46c5-91ee-a359264524d9.png)


如果测试遇到问题再反馈

**Comment by allanpk716** [comment]
调整保存字幕的格式后，记得重启容器，启动阶段会进行所有字幕的格式调整，这个耗时多久基于有多少字幕。
