### ISSUE TITLE
在库中手动搜索字幕www.a4k.net跳转链接参数错误

### ISSUE THREAD

**Issue by markvlenvision** [ChineseSubFinder/ChineseSubFinder#684]
目前，插件中的链接是：https://a4k.net/search?keyword=xxxx，
,keyword 参数无效，应该是：key
改为https://a4k.net/search?key=xxxx
![qqq](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/46559300/fbb6f073-038e-44ff-8a0b-a1491a1ceabe)

**Comment by latel** [comment]
这网站是不是已经关了？

**Comment by markvlenvision** [comment]
> 这网站是不是已经关了？
貌似，，，是的。
