### ISSUE TITLE
win11下，启动软件，没有任何显示，而且网站也打不开，用管理员身份启动也不行

### ISSUE THREAD

**Issue by chenchenno11** [ChineseSubFinder/ChineseSubFinder#700]
![photo_2023-09-25_11-50-05](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/142315291/346c7b91-8c54-46b1-9ddd-49502ae20b30)
![photo_2023-09-25_11-30-39](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/142315291/f57905c7-2665-4f9c-8e44-416a9f93e6fa)

如图win11下，启动软件，没有任何显示，而且网站也打不开，用管理员身份启动也不行

**Comment by allanpk716** [comment]
同级目录下是 Log 有输出信息吗？

**Comment by chenchenno11** [comment]
> 同级目录下是 Log 有输出信息吗？

啥意思，cmd窗口没有任何反应，下载下来的久3个东西exe .LICENSE文件，md文件，其中LICENSE文件不知道怎么打开
![屏幕截图 2023-09-26 113550](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/142315291/5aaa3274-cfd0-45ee-81bc-8fad9baff393)

**Comment by allanpk716** [comment]
只需要运行主程序：chinesesubfinder.exe 正常自动在当前目录新建 Log 文件夹。其他两个信息是自动编译输出的，无需关心。

**Comment by chenchenno11** [comment]
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/142315291/ae75d2fb-3490-4740-85a5-a6d44ab145e3)
没有log文件夹，没任何反应

**Comment by chenchenno11** [comment]
![Uploading image.png…]()并没有log文件啊

**Comment by chenchenno11** [comment]
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/142315291/510f4518-fda8-4c97-a5d4-d5d1c3e49af7)
并没有log文件夹啊，什么反应都没有

**Comment by allanpk716** [comment]
按 https://blog.csdn.net/weixin_44120025/article/details/118651103  类似的思路和工具，查看少了什么支持库
