### ISSUE TITLE
容器自動重啟 無法繼續運行

### ISSUE THREAD

**Issue by xiNeRoar** [ChineseSubFinder/ChineseSubFinder#701]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: latest
>
> 环境: docker or Window or Linux or MAC
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

容器自動重啟

## 你的问题弄重现嘛？

> 能够重新，能够重现

## 请给出当次问题的完整日志

[INFO]: 2023-09-25 04:55:56 - Hotfix 007 is Recorded
[INFO]: 2023-09-25 04:55:56 - PreJob.HotFix() End
[INFO]: 2023-09-25 04:55:56 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2023-09-25 04:55:56 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-09-25 04:55:56 - PreJob.ChangeSubNameFormat() End
[INFO]: 2023-09-25 04:55:56 - PreJob.Wait() Done.
[INFO]: 2023-09-25 04:55:56 - Download.SupplierCheck() Start ...
[INFO]: 2023-09-25 04:55:56 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-09-25 04:55:56 - PreDownloadProcess.Init() Start...
[INFO]: 2023-09-25 04:55:56 - ClearRodTmpRootFolder Done
[INFO]: 2023-09-25 04:55:56 - PreDownloadProcess.Init() End
[INFO]: 2023-09-25 04:55:56 - PreDownloadProcess.Check() Start...
[INFO]: 2023-09-25 04:55:56 - UseHttpProxy = false
[INFO]: 2023-09-25 04:55:59 - UrlConnectednessTest Target Site https://baidu.com Speed: 2718 ms, Status: true
[INFO]: 2023-09-25 04:55:59 - Check Sub Supplier Start...
[INFO]: 2023-09-25 04:56:02 - xunlei Check Alive = true, Speed = 3162 ms
[INFO]: 2023-09-25 04:56:03 - shooter Check Alive = true, Speed = 974 ms
2023/09/25 04:56:03.425233 ERROR RESTY Get "https://www.a4k.net": dial tcp: lookup www.a4k.net on 169.254.169.254:53: no such host, Attempt 1
2023/09/25 04:56:03.527597 ERROR RESTY Get "https://www.a4k.net": dial tcp: lookup www.a4k.net on 169.254.169.254:53: no such host, Attempt 2
[ERROR]: 2023-09-25 04:56:03 - a4k CheckAlive.Get Get "https://www.a4k.net": dial tcp: lookup www.a4k.net on 169.254.169.254:53: no such host
[WARNING]: 2023-09-25 04:56:03 - a4k Check Alive = false
[INFO]: 2023-09-25 04:56:03 - Alive Supplier: xunlei
[INFO]: 2023-09-25 04:56:03 - Alive Supplier: shooter
[INFO]: 2023-09-25 04:56:03 - Alive Supplier: a4k
[INFO]: 2023-09-25 04:56:03 - Check Sub Supplier End
[WARNING]: 2023-09-25 04:56:03 - MoviePaths not set, len == 0
[WARNING]: 2023-09-25 04:56:03 - SeriesPaths not set, len == 0
[INFO]: 2023-09-25 04:56:03 - PreDownloadProcess.Check() End
[INFO]: 2023-09-25 04:56:03 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-09-25 04:56:03 - Download.SupplierCheck() End
[INFO]: 2023-09-25 04:56:03 - Need do Setup
[INFO]: 2023-09-25 04:56:03 - Try Start Http Server At Port 19035
[INFO]: 2023-09-25 05:18:22 - Http Server Shutdown Successfully
[INFO]: 2023-09-25 05:18:22 - VideoScanAndRefreshHelper is not running
[INFO]: 2023-09-25 05:18:22 - Http Server Shutdown Done.
[INFO]: 2023-09-25 05:18:22 - Try Start Http Server At Port 19035
[INFO]: 2023-09-25 05:18:31 - ------------------------------------
[INFO]: 2023-09-25 05:18:31 - Video Scan Started By webui...
[INFO]: 2023-09-25 05:18:31 - ---------------------------------
[INFO]: 2023-09-25 05:18:31 - GetPathUrlMap
[INFO]: 2023-09-25 05:18:31 - pathUrlMap /media/media/Movies /movie_dir_0
[INFO]: 2023-09-25 05:18:31 - pathUrlMap /media/media/TV Shows /series_dir_0
[INFO]: 2023-09-25 05:18:31 - pathUrlMap /media/media/Anime /series_dir_1
[INFO]: 2023-09-25 05:18:31 - ---------------------------------
[INFO]: 2023-09-25 05:18:31 - ScanNormalMovieAndSeries Start...
[INFO]: 2023-09-25 05:18:31 - ------------------------------------------
[INFO]: 2023-09-25 05:18:31 - GetSeriesListFromDirs Start...
[INFO]: 2023-09-25 05:18:31 -  --------------------------------------------------
[INFO]: 2023-09-25 05:18:31 - MatchedVideoFileFromDirs Start...
[INFO]: 2023-09-25 05:19:39 - VideoScanAndRefreshHelper is not running
[INFO]: 2023-09-25 05:19:39 - Http Server Shutdown Successfully
[INFO]: 2023-09-25 05:19:39 - Http Server Shutdown Done.
[INFO]: 2023-09-25 05:19:39 - Try Start Http Server At Port 19035
[INFO]: 2023-09-25 05:20:03 - Tmdb Api is Alive 279
[INFO]: 2023-09-25 05:20:03 - tmdbApi.Alive() == true
[INFO]: 2023-09-25 05:20:06 - Tmdb Api is Alive 279
[INFO]: 2023-09-25 05:20:06 - tmdbApi.Alive() == true
[INFO]: 2023-09-25 05:20:08 - VideoScanAndRefreshHelper is not running
[INFO]: 2023-09-25 05:20:08 - Http Server Shutdown Successfully
[INFO]: 2023-09-25 05:20:08 - Http Server Shutdown Done.
[INFO]: 2023-09-25 05:20:08 - Tmdb Api is Alive 279
[INFO]: 2023-09-25 05:20:08 - Try Start Http Server At Port 19035
[INFO]: 2023-09-25 05:20:14 - ------------------------------------
[INFO]: 2023-09-25 05:20:14 - Video Scan Started By webui...
[INFO]: 2023-09-25 05:20:14 - ---------------------------------
[INFO]: 2023-09-25 05:20:14 - GetPathUrlMap
[INFO]: 2023-09-25 05:20:14 - pathUrlMap /media/media/Movies /movie_dir_0
[INFO]: 2023-09-25 05:20:14 - pathUrlMap /media/media/TV Shows /series_dir_0
[INFO]: 2023-09-25 05:20:14 - pathUrlMap /media/media/Anime /series_dir_1
[INFO]: 2023-09-25 05:20:14 - ---------------------------------
[INFO]: 2023-09-25 05:20:14 - ScanNormalMovieAndSeries Start...
[INFO]: 2023-09-25 05:20:14 - ------------------------------------------
[INFO]: 2023-09-25 05:20:14 - GetSeriesListFromDirs Start...
[INFO]: 2023-09-25 05:20:14 -  --------------------------------------------------
[INFO]: 2023-09-25 05:20:14 - MatchedVideoFileFromDirs Start...
[INFO]: 2023-09-25 05:26:01 - GetSeriesListFromDirs End
[INFO]: 2023-09-25 05:26:01 - ------------------------------------------
[INFO]: 2023-09-25 05:26:01 - GetSeriesListFromDirs End
[INFO]: 2023-09-25 05:26:01 - ------------------------------------------
[INFO]: 2023-09-25 05:52:38 - RunAtStartup: false, so will not Run At Startup
[INFO]: 2023-09-25 05:52:38 - CronHelper Start...
[INFO]: 2023-09-25 05:52:38 - Next Sub Scan Will Process At: 2023-09-25 09:52:38
[INFO]: 2023-09-25 06:08:45 - MatchedVideoFileFromDirs End
[INFO]: 2023-09-25 06:08:45 -  --------------------------------------------------
[INFO]: 2023-09-25 06:08:45 - MatchedVideoFileFromDirs End
[INFO]: 2023-09-25 06:08:45 -  --------------------------------------------------
[INFO]: 2023-09-25 06:08:45 - ScanNormalMovieAndSeries End
[INFO]: 2023-09-25 06:08:45 - ScanNormalMovieAndSeries End
panic: send on closed channel
goroutine 225 [running]:
github.com/ChineseSubFinder/ChineseSubFinder/pkg/lock.Lock.Unlock(...)
	/root/go/src/pkg/lock/lock.go:29
github.com/ChineseSubFinder/ChineseSubFinder/internal/backend/controllers/v1.(*ControllerBase).RefreshMainList.func2.1()
	/root/go/src/internal/backend/controllers/v1/video_list_v2.go:54 +0x4c
github.com/ChineseSubFinder/ChineseSubFinder/internal/backend/controllers/v1.(*ControllerBase).RefreshMainList.func2()
	/root/go/src/internal/backend/controllers/v1/video_list_v2.go:74 +0x46c
created by github.com/ChineseSubFinder/ChineseSubFinder/internal/backend/controllers/v1.(*ControllerBase).RefreshMainList
	/root/go/src/internal/backend/controllers/v1/video_list_v2.go:38 +0xbc
已设置 PERMS=true，重设 '/media' 目录权限为 0:0 所有（媒体文件多，花的时间也多，耐心等）...

**Comment by allanpk716** [comment]
日志上有提示

已设置 PERMS=true，重设 '/media' 目录权限为 0:0 所有（媒体文件多，花的时间也多，耐心等）...

**Comment by xiNeRoar** [comment]
明白 以為是BUG 謝謝
