### ISSUE TITLE
重新安装chinesesubfinder后出现无法启动：运行日志提示exec /sbin/tini:permission denied权限问题

### ISSUE THREAD

**Issue by LmanTs** [ChineseSubFinder/ChineseSubFinder#705]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

>allanpk716/chinesesubfinder:latest
>unraid系统docker-compose部署

## 你遇到什么问题了？
程序提示了权限问题，并且无法启动容器
> 目前我尝试通过unraid的应用商店直接安装和docker-compose安装均出现这个权限问题，出现这个问题是在我操作了删除docker的配置文件后（系统的），重新安装chinesesubfinder后出现的这个问题，尝试过修改配置中的PUID和PGID，分别为1000、99、0三个

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 希望知道如何解决

## 给出当前程序的配置文件

> 由于权限问题，系统没有创建config

## 如果是使用 Docker，请给出对应的配置信息

>docker-compose.yml配置信息如下： 
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder
    volumes:
      - /mnt/disk1/appdata/chinesesubfinder/config:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mmt/user/media:/media    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /mnt/disk1/appdata/chinesesubfinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=0         # uid
      - PGID=0          # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=000         # 权限掩码
    restart: always
    network_mode: host
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035  # 从0.20.0版本开始，通过webui来设置
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整

## 给出媒体文件夹的目录结构

> 非目录问题

## 请给出当次问题的完整日志

> 由于权限问题，未生成
> 运行日志中提示exec /sbin/tini:permission denied

**Comment by allanpk716** [comment]
你看看是否可以给到最高权限给到这个容器，一劳永逸

**Comment by LmanTs** [comment]
感谢您的回复，我想问一下puid设置为0应该就是root账户了吧？

**Comment by allanpk716** [comment]
@devome 类似这样的问题，有办法给出一个通用的教程吗？:joy:

**Comment by devome** [comment]
你在compose文件中添加entrypoint覆盖容器自身设置试试：
```
  entrypoint: ["/sbin/tini", "/usr/bin/entrypoint.sh"]
```

**Comment by LmanTs** [comment]
> 你在compose文件中添加entrypoint覆盖容器自身设置试试：
> ```
>   entrypoint: ["/sbin/tini", "/usr/bin/entrypoint.sh"]
> ```

谢谢您的解答，不过群里的大佬看了之后表示可能是固件问题，小概率事件，docker引发的，更新最新的镜像已经得到解决了
