### ISSUE TITLE
查找不到字幕

### ISSUE THREAD

**Issue by xiNeRoar** [ChineseSubFinder/ChineseSubFinder#71]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.17.4

环境: docker on Synology

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/66216186/136473492-d19514d7-3a0f-469c-9221-1e0568e45a79.png)
昨天下載的電影，電影裡面本身只有英文字幕沒有中文字幕，程式跑完之後沒有找到中文字幕，但我人手在subhd用同樣的關鍵字卻找得到
![image](https://user-images.githubusercontent.com/66216186/136473625-d29f67b4-598a-4d0c-b513-2e404e773300.png)

## 你的问题弄重现嘛？

不知道

## 你期望的结果

應該找到字幕

**Comment by allanpk716** [comment]
有没有进行过削刮，日志上下文多截取一些发上来

**Comment by xiNeRoar** [comment]
![image](https://user-images.githubusercontent.com/66216186/136500737-af8836c6-b8d2-41b0-88f3-6eb294b84c3d.png)
這樣嗎?
