### ISSUE TITLE
无法配置电影和连续剧目录

### ISSUE THREAD

**Issue by rozbo** [ChineseSubFinder/ChineseSubFinder#713]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.55.1
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

无法配置电影和连续剧目录

## 你的问题弄重现嘛？

> 能够重新

## issue
类似 https://github.com/ChineseSubFinder/ChineseSubFinder/issues/562 的问题，但看那里被close了，而且感觉那边沟通是不是存在什么误会，我尽量详细的再阐述一遍看看究竟是什么问题。

首先有文件架构如下(其实就是推荐的结构)
```
video/movie/
	├─The Night House (2021)
	│      clearlogo.png
	│      fanart.jpg
	│      landscape.jpg
	│      movie.xml
	│      poster.jpg
	│      The Night House (2021) Bluray-1080p.chinese(简英,subhd).ass
	│      The Night House (2021) Bluray-1080p.chinese(简英,zimuku).default.ass
	│      The Night House (2021) Bluray-1080p.mkv
	│      The Night House (2021) Bluray-1080p.nfo
	│      
	└─Dune (2021)
			clearlogo.png
			Dune (2021) WEBRip-1080p.chinese(简,shooter).srt
			Dune (2021) WEBRip-1080p.chinese(简,xunlei).srt
			Dune (2021) WEBRip-1080p.chinese(简英,shooter).ass
			Dune (2021) WEBRip-1080p.chinese(简英,xunlei).ass
			Dune (2021) WEBRip-1080p.chinese(简英,zimuku).default.ass
			Dune (2021) WEBRip-1080p.mkv
			Dune (2021) WEBRip-1080p.nfo
			fanart.jpg
			landscape.jpg
			movie.xml
			poster.jpg
```

这个结构下，文件夹的所有权限都已经修改完毕，此时我们把video映射为 media
```
    volumes:
      - ./cnsub_config:/config   # 冒号左边请修改为你想保存配置的路径
      - /volume2/video:/media
```
正常情况下， `/media/movie` 应该是合法且可用的目录吧？但是目前系统会认为此目录不可用。(已经排除过权限问题为前提)
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/7907969/1215ddf5-5be2-4d73-a08f-f4d8b8d0b346)
并且，假如此时我们手动进docker shell里

```bash
cd /media
mkdir test
chown 1026:100 test
chmod 777 test
```
按道理， /media/test这下肯定是存在且权限正确吧
```
drwxrwxrwx    1 1026     users            0 Oct 20 00:55 test
```
但事实上，
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/7907969/88b6a7ea-bafc-4694-b162-ceb82a87b454)

再换个思路，此时我们直接映射 movie 为 /movie
```yaml
    volumes:
      - ./cnsub_config:/config   # 冒号左边请修改为你想保存配置的路径
      # - /volume2/video:/media
      - /volume2/video/movie:/movie
```
此时检测结果正常
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/7907969/b056b80e-61c8-4754-b15f-6c99252d1b73)
这也侧面说明了权限是没有问题的。
但是将无法保存
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/7907969/65ffc7a2-70de-43ff-becb-21dec8d1d092)

这是什么鬼？
貌似现阶段能行的是，重复映射，先映射/media，再把子目录也映射进来，但这显然是不符合docker的最佳实践的。。。吧？

**Comment by allanpk716** [comment]
这部分需要咨询 @devome 是否能协助定位问题。以及环境变量 PERMS 是否设置为 true？或者至少执行过一次后才设置为 false

**Comment by devome** [comment]
chown 1026:100 test只是修改了test这个文件夹的权限，下层文件夹及文件可能并未修正。请使用`chown -R 1026:100 test`来遍历。

**Comment by rozbo** [comment]
@devome 没有加-R是因为这个test是上一步刚建的，里面没有子目录和文件。
环境变量里有PERMS=true，并且怕这个不保险，还在host里手动chown -R 1026:100 /volume2/video 了。
给777是临时测试用的，因为按道理，即便是owner不对，777也应该是有权限的，但系统依然认为没有权限。
并且，直接映射到一级目录 /movie 时，系统也能够检测到权限正常，但映射到 /media/movie就不行。

综上，我个人的看法是在这种情况下，文件是确实存在的，权限也是正确的，但是二级目录就不行，一级目录就识别正确，但是系统也不允许使用一级目录。

**Comment by rozbo** [comment]
这种情况，在我引用的哪个issue里也有多个人提及
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/7907969/df56b08e-fafd-4314-8d73-23d3bca5aa0e)

包括现在这种重复映射将就能使的办法也是从哪里学到的
![image](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/7907969/f05e02d9-7055-4b3c-93ab-f9a701440def)

虽然不符合docker的最佳实践，但这种重复映射的办法是目前唯一可行的办法了。。

**Comment by rozbo** [comment]
docker的宿主机也相当重要， 是不是宿主机的内核不一致导致了这种判断方法在不同的nas上有不同的表现？
有没有可能把这里的权限修改下，改成警告而非错误呢，或者放开限制一级目录必须为/media也可以吧。

**Comment by allanpk716** [comment]
> docker的宿主机也相当重要， 是不是宿主机的内核不一致导致了这种判断方法在不同的nas上有不同的表现？ 有没有可能把这里的权限修改下，改成警告而非错误呢，或者放开限制一级目录必须为/media也可以吧。

就是最简单判断是否是文件夹，如果这都无法通过，放宽 /media 程序也不可能通过后续更加复杂的逻辑判断

https://github.com/allanpk716/ChineseSubFinder/blob/0df745b6b1e925ebe73823e1eacab038a8097854/internal/backend/controllers/base/path_things.go#28

**Comment by rozbo** [comment]
现在来看，似乎真的是isDir这个逻辑有点瑕疵？
没看后续逻辑，但目前来看，假如放宽 /media 限制，比如 /volume2/video/movie 直接映射到 /movie， 此时movie是可以通过权限检测的（已测，上面有截图）
现在我是用重复映射的方式能正常运行的，即/media 随便映射一个目录，然后把其余子目录再分别映射到 /media下，这种方式可以正常工作，就证明了文件确实是存在，并且权限没问题的。（况且777权限都无法使这个isDir返回为true）


这里我有个推测，有没有可能像群晖这样的系统里，map进去的二级目录不是典型意义的文件夹？可能是链接之类的东西
https://github.com/ChineseSubFinder/ChineseSubFinder/blob/ea8bd6d2600e209259b44e566b6a8e950f1ed8bb/pkg/util.go#L189-L190
看能否把这里的os.Stat(path) 改成 `os.Lstat(path) ` ，这个`Lstat`是可以传统链接的，但Stat不行。
