### ISSUE TITLE
能否做个有GUI显示的WINDOWS程序？

### ISSUE THREAD

**Issue by dskblh** [ChineseSubFinder/ChineseSubFinder#78]
感谢作者，刚才试用了一下，软件非常好用。
提个建议如题，CLI形式的总感觉不够直观，或者能在目前的显示模式下，加入扫描完成后的本次扫描结果总体统计数据，不然都不知道他成功了多少，失败了多少？因为貌似扫描完毕后他就自动关闭对话框了，想看结果只能去查日志了。

**Comment by allanpk716** [comment]
> 感谢作者，刚才试用了一下，软件非常好用。 提个建议如题，CLI形式的总感觉不够直观，或者能在目前的显示模式下，加入扫描完成后的本次扫描结果总体统计数据，不然都不知道他成功了多少，失败了多少？因为貌似扫描完毕后他就自动关闭对话框了，想看结果只能去查日志了。

1. 你是在 Windows 下使用吗？正常应该不会关闭对话框的，因为逻辑是固定间隔去扫描
2. 统计功能暂时没有计划，我想一下怎么去记录和展示什么内容先
3. 应该会做 Web 的客户端，但是没那么快，最近在做其他的功能（字幕时间轴校正等）
