### ISSUE TITLE
MovieFolder not found

### ISSUE THREAD

**Issue by sapipoZZZ** [ChineseSubFinder/ChineseSubFinder#86]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: docker   v0.18.0 

环境: docker  on  群辉

## 你遇到什么问题了？

配置相关的挂盘和yaml后，启动报错：MovieFolder not found

## 你的问题弄重现嘛？

是，100%重现

## 你期望的结果

希望能解决这个bug

## 可以提供遇到问题时候，电影、连续剧的信息吗？
挂盘信息：
/volume2/docker/chineseSubfinder	/config
/volume1/video	/meida

电影存放位置：
/volume1/video/movie/飞机总动员 (2013)/飞机总动员.mkv

config.yaml:
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 6h
Threads: 4
RunAtStartup: true
MovieFolder: /media/movie
SeriesFolder: /media/drama
DebugMode: false
SaveMultiSub: false

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume2/docker/chinesesubfinder/logs:/app/Logs

(EE) 
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE) 

[INFO]: 2021-10-22 08:01:49 - ChineseSubFinder Version: v0.18.0 | stdout
[INFO]: 2021-10-22 08:01:49 - UseProxy = false
[ERROR]: 2021-10-22 08:01:49 - MovieFolder not found

**Comment by OkkusiNn** [comment]
同样的问题 群晖的docker 使用volume2 就可以读取 用volume1就不行 后来PUID GUID换成0成功访问

**Comment by 2ue** [comment]
你好，目录映射关系如下：
/mnt/user/media/ -> /media/
是直接把本地媒体库根目录映射到容器的/mdeia/下，未做其他任何映射关系

运行容器后在config.yaml文件下看到有默认设置
![image](https://user-images.githubusercontent.com/13751432/205421288-93f667ae-9e5a-47fb-a70c-d55498502cbd.png)

然后docker日志一直输出：
![image](https://user-images.githubusercontent.com/13751432/205421357-100a519d-7502-4df6-a252-210fe49e38db.png)

请问这个应该怎么修改呢？我本地目录是媒体目录是/mnt/user/media/movie、/mnt/user/media/tv，/mnt/user/media/cg

**Comment by allanpk716** [comment]
> 你好，目录映射关系如下： /mnt/user/media/ -> /media/ 是直接把本地媒体库根目录映射到容器的/mdeia/下，未做其他任何映射关系
> 
> 运行容器后在config.yaml文件下看到有默认设置 ![image](https://user-images.githubusercontent.com/13751432/205421288-93f667ae-9e5a-47fb-a70c-d55498502cbd.png)
> 
> 然后docker日志一直输出： ![image](https://user-images.githubusercontent.com/13751432/205421357-100a519d-7502-4df6-a252-210fe49e38db.png)
> 
> 请问这个应该怎么修改呢？我本地目录是媒体目录是/mnt/user/media/movie、/mnt/user/media/tv，/mnt/user/media/cg

看最新教程。
